"use client";
import {AlertTriangle,ArrowLeft,Check,Clock3,Coins,Crown,Eye,Gift,Heart,Image as ImageIcon,LockKeyhole,Phone,Search,ShieldCheck,UserRoundX} from "lucide-react";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {blockUser,currentUser,reportCategories,reportUser,subscribe,unblockUserRemote,uploadReportEvidence,type CommunityProfile,type ReportCategory} from "@/lib/community-service";

type Mode="safety"|"report"|"block"|"visitors"|"gifts"|"photos";
type ReportRow={id:string;category:string;details:string|null;status:string;created_at:string;reported_id:string};
type BlockRow={blocked_id:string;reason:string|null;created_at:string;fc_profiles?:CommunityProfile|null};
type VisitRow={id:number;viewer_id:string;viewed_at:string;seen:boolean;fc_profiles?:CommunityProfile|null};
type GiftRow={id:string;name:string;emoji:string;coin_cost:number;premium_only:boolean};
type GiftEvent={id:string;gift_id:string;coin_cost:number;created_at:string;sender_id:string;recipient_id:string};type Transaction={id:string;amount:number;kind:string;description:string;created_at:string};
export function CommunityHub({mode}:{mode:Mode}){
 const supabase=useMemo(()=>createClient(),[]),[uid,setUid]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[reports,setReports]=useState<ReportRow[]>([]),[blocks,setBlocks]=useState<BlockRow[]>([]),[visits,setVisits]=useState<VisitRow[]>([]),[gifts,setGifts]=useState<GiftRow[]>([]),[giftEvents,setGiftEvents]=useState<GiftEvent[]>([]),[transactions,setTransactions]=useState<Transaction[]>([]),[balance,setBalance]=useState(0),[premium,setPremium]=useState(false),[profiles,setProfiles]=useState<CommunityProfile[]>([]),[target,setTarget]=useState(""),[category,setCategory]=useState<ReportCategory>("Fake Profile"),[details,setDetails]=useState(""),[contact,setContact]=useState({name:"",phone:""}),[evidence,setEvidence]=useState<File|null>(null);
 const load=useCallback(async()=>{try{const user=await currentUser();setUid(user.id);const [{data:people},{data:me},{data:reportData},{data:blockData},{data:visitData},{data:giftData},{data:wallet},{data:contactData},{data:eventData},{data:transactionData}]=await Promise.all([supabase.from("fc_profiles").select("id,display_name,username,last_seen_at,premium").neq("id",user.id).limit(100),supabase.from("fc_profiles").select("premium").eq("id",user.id).single(),supabase.from("fc_reports").select("id,category,details,status,created_at,reported_id").order("created_at",{ascending:false}),supabase.from("fc_blocks").select("blocked_id,reason,created_at").order("created_at",{ascending:false}),supabase.from("fc_profile_visits").select("id,viewer_id,viewed_at,seen").order("viewed_at",{ascending:false}),supabase.from("fc_gifts").select("id,name,emoji,coin_cost,premium_only").order("coin_cost"),supabase.from("fc_coin_wallets").select("balance").maybeSingle(),supabase.from("fc_safety_contacts").select("name,phone").maybeSingle(),supabase.from("fc_gift_events").select("id,gift_id,coin_cost,created_at,sender_id,recipient_id").order("created_at",{ascending:false}).limit(100),supabase.from("fc_coin_transactions").select("id,amount,kind,description,created_at").order("created_at",{ascending:false}).limit(100)]);setProfiles(people??[]);setPremium(Boolean(me?.premium));setReports(reportData??[]);setBlocks(blockData??[]);setVisits(visitData??[]);setGifts(giftData??[]);setGiftEvents(eventData??[]);setTransactions(transactionData??[]);setBalance(wallet?.balance??0);if(contactData)setContact(contactData);if(!target&&people?.[0])setTarget(people[0].id)}catch(error){setNotice(error instanceof Error?error.message:"Unable to load")}finally{setLoading(false)}},[supabase,target]);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("to");if(requested)setTarget(requested);void load()},[load]);useEffect(()=>{if(!uid)return;const specs=mode==="gifts"?[["fc_gift_events",`recipient_id=eq.${uid}`],["fc_coin_wallets",`user_id=eq.${uid}`],["fc_coin_transactions",`user_id=eq.${uid}`]]:mode==="visitors"?[["fc_profile_visits",`viewed_id=eq.${uid}`]]:mode==="photos"?[["fc_profile_photos",`user_id=eq.${uid}`]]:mode==="block"?[["fc_blocks",`blocker_id=eq.${uid}`]]:[["fc_reports",`reporter_id=eq.${uid}`]];const cleanups=specs.map(([table,filter])=>subscribe(table,filter,()=>void load()));return()=>cleanups.forEach(cleanup=>cleanup())},[uid,mode,load]);
 const profile=(id:string)=>profiles.find(x=>x.id===id),run=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);try{await action();setNotice(message);await load()}catch(error){setNotice(error instanceof Error?error.message:"Action failed")}finally{setBusy(false)}};
 const title={safety:"Safety Center",report:"Report a member",block:"Blocked members",visitors:"Profile visitors",gifts:"Gifts & Coins",photos:"Photo moderation"}[mode];
 if(loading)return <main className="community-page"><div className="community-shell"><p>Loading secure Flirtschat data…</p></div></main>;
 return <main className="community-page"><header><Link href="/dashboard"><ArrowLeft/></Link><div><small>FLIRTSCHAT TRUST</small><h1>{title}</h1></div><ShieldCheck/></header><div className="community-shell">{mode==="safety"&&<Safety reports={reports} contact={contact} setContact={setContact} save={()=>run(async()=>{const user=await currentUser();const {error}=await supabase.from("fc_safety_contacts").upsert({user_id:user.id,...contact});if(error)throw error},"Safety contact saved")}/>} {mode==="report"&&<><Panel title="Private report" icon={<AlertTriangle/>}><label>Member<select value={target} onChange={e=>setTarget(e.target.value)}>{profiles.map(p=><option value={p.id} key={p.id}>{p.display_name||p.username}</option>)}</select></label><div className="category-grid">{reportCategories.map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tell our safety team what happened"/><label>Optional private evidence<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setEvidence(e.target.files?.[0]??null)}/></label><button className="primary" disabled={busy||!target} onClick={()=>run(async()=>{const key=evidence?await uploadReportEvidence(evidence):undefined;await reportUser(target,category,details,undefined,key);setEvidence(null);setDetails("")},"Report submitted securely")}>{busy?"Submitting…":"Submit report"}</button></Panel><ReportHistory rows={reports}/></>} {mode==="block"&&<><Panel title="Block a member" icon={<UserRoundX/>}><label>Member<select value={target} onChange={e=>setTarget(e.target.value)}>{profiles.map(p=><option value={p.id} key={p.id}>{p.display_name||p.username}</option>)}</select></label><button className="danger" disabled={busy||!target} onClick={()=>run(()=>blockUser(target),"Member blocked")}>Block member</button></Panel><div className="community-cards">{blocks.length?blocks.map(x=><Card key={x.blocked_id} icon={<UserRoundX/>} title={profile(x.blocked_id)?.display_name||profile(x.blocked_id)?.username||"Flirtschat member"} copy={x.reason||"Blocked"}><button onClick={()=>run(()=>unblockUserRemote(x.blocked_id),"Member unblocked")}>Unblock</button></Card>):<p>No blocked members.</p>}</div></>} {mode==="visitors"&&<Visitors rows={visits} profiles={profiles} premium={premium}/>} {mode==="gifts"&&<Gifts gifts={gifts} profiles={profiles} target={target} setTarget={setTarget} balance={balance} events={giftEvents} transactions={transactions} run={run}/>} {mode==="photos"&&<Photos/>}</div>{notice&&<div className="community-toast"><Check/>{notice}</div>}</main>
}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="community-panel"><header><i>{icon}</i><h2>{title}</h2></header>{children}</section>}
function Card({icon,title,copy,children}:{icon:React.ReactNode;title:string;copy:string;children?:React.ReactNode}){return <article className="community-card"><i>{icon}</i><span><strong>{title}</strong><small>{copy}</small></span>{children}</article>}
function Safety({reports,contact,setContact,save}:{reports:ReportRow[];contact:{name:string;phone:string};setContact:(x:{name:string;phone:string})=>void;save:()=>void}){return <><section className="safety-hero"><ShieldCheck/><div><h2>Your safety comes first</h2><p>Use private reporting, blocking, trusted contacts, and practical tips whenever something feels wrong.</p></div></section><div className="community-grid"><Panel title="Safety tips" icon={<LockKeyhole/>}><ul><li>Meet in a busy public place.</li><li>Tell a trusted person your plans.</li><li>Never send money or financial details.</li><li>Keep your own transport and trust your instincts.</li></ul></Panel><Panel title="Emergency contact" icon={<Phone/>}><label>Name<input value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/></label><label>Phone<input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label><button className="primary" onClick={save}>Save contact</button></Panel><Panel title="Community Guidelines" icon={<Heart/>}><ul><li>Be authentic, respectful, and consensual.</li><li>No hate, harassment, scams, nudity, or underage users.</li><li>Report unsafe behavior—reports stay private.</li></ul></Panel></div><div className="community-actions"><Link href="/report">Report user</Link><Link href="/block">Block or unblock</Link></div><ReportHistory rows={reports}/></>}
function ReportHistory({rows}:{rows:ReportRow[]}){return <Panel title="Report history" icon={<Clock3/>}><div className="community-cards">{rows.length?rows.map(x=><Card key={x.id} icon={<AlertTriangle/>} title={x.category} copy={`${x.status} · ${new Date(x.created_at).toLocaleString()}`}/>):<p>No reports submitted.</p>}</div></Panel>}
function Visitors({rows,profiles,premium}:{rows:VisitRow[];profiles:CommunityProfile[];premium:boolean}){const visible=premium?rows:rows.slice(0,5);return <><section className="feature-note"><Eye/><span><strong>{rows.length} profile views</strong><small>{premium?"Premium unlimited history":"Free plan shows the latest 5 visitors"}</small></span></section><div className="community-cards">{visible.length?visible.map(v=>{const p=profiles.find(x=>x.id===v.viewer_id),online=p&&Date.now()-new Date(p.last_seen_at).getTime()<300000;return <Card key={v.id} icon={<Eye/>} title={p?.display_name||p?.username||"Flirtschat member"} copy={`${new Date(v.viewed_at).toLocaleString()}${online?" · Online":""}`}>{!v.seen&&<b className="new-badge">NEW</b>}</Card>}):<p>No visitors yet.</p>}</div></>}
function Gifts({gifts,profiles,target,setTarget,balance,events,transactions,run}:{gifts:GiftRow[];profiles:CommunityProfile[];target:string;setTarget:(x:string)=>void;balance:number;events:GiftEvent[];transactions:Transaction[];run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const supabase=createClient();return <><section className="coin-balance"><Coins/><span><small>Coin balance</small><strong>{balance}</strong></span><button onClick={()=>run(async()=>await supabase.rpc("fc_claim_daily_reward"),"Daily reward claimed")}>Daily reward</button></section><label className="recipient"><Search/>Send to<select value={target} onChange={e=>setTarget(e.target.value)}>{profiles.map(p=><option value={p.id} key={p.id}>{p.display_name||p.username}</option>)}</select></label><div className="gift-grid">{gifts.map(g=><button key={g.id} onClick={()=>run(async()=>await supabase.rpc("fc_send_gift",{recipient:target,gift:g.id,gift_message:null}),`${g.name} sent!`)}><span>{g.emoji}</span><strong>{g.name}</strong><small>{g.coin_cost} coins</small>{g.premium_only&&<em><Crown/>Premium</em>}</button>)}</div><Panel title="Gift history" icon={<Gift/>}><div className="community-cards">{events.length?events.map(e=><Card key={e.id} icon={<Gift/>} title={gifts.find(g=>g.id===e.gift_id)?.name||e.gift_id} copy={`${e.coin_cost} coins · ${new Date(e.created_at).toLocaleString()}`}/>):<p>No gifts yet.</p>}</div></Panel><Panel title="Transaction history" icon={<Coins/>}><div className="community-cards">{transactions.length?transactions.map(t=><Card key={t.id} icon={<Coins/>} title={t.description||t.kind} copy={`${t.amount>0?"+":""}${t.amount} · ${new Date(t.created_at).toLocaleString()}`}/>):<p>No transactions yet.</p>}</div></Panel></>}
function Photos(){const [photos,setPhotos]=useState<Array<{id:string;object_key:string;moderation_status:string;moderator_notes:string|null}>>([]);useEffect(()=>{const supabase=createClient();void supabase.from("fc_profile_photos").select("id,object_key,moderation_status,moderator_notes").order("created_at",{ascending:false}).then(({data})=>setPhotos(data??[]))},[]);return <><section className="feature-note"><ImageIcon/><span><strong>Cloudflare R2 photo review</strong><small>Pending photos remain blurred until approved. AI metadata is ready in Supabase.</small></span></section><div className="photo-grid">{photos.map(p=><article className={p.moderation_status} key={p.id}><div><ImageIcon/></div><strong>{p.moderation_status}</strong><small>{p.moderator_notes||"Awaiting moderator review"}</small><Link href={`/report?photo=${p.id}`}>Report image</Link></article>)}</div></>}
