"use client";
/* eslint-disable @next/next/no-img-element -- private post media uses the authenticated media route. */

import {ArrowLeft,Bookmark,Heart,MessageCircle,Share2} from "lucide-react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useCallback,useEffect,useState} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {DesktopSidebar} from "@/components/dashboard/desktop-sidebar";
import {ProfileImage} from "@/components/profile-image";
import {useCurrentProfile} from "@/components/profile/current-profile-provider";
import {FlirtschatLoader} from "@/components/ui/flirtschat-loader";
import {PostComments} from "@/components/global/post-comments";
import {deletePostComment,loadGlobalPost,loadPostComments,postImageUrl,recordPostShare,togglePostHeart,togglePostSave,type GlobalComment,type GlobalPost} from "@/lib/global-feed-service";
import {createClient} from "@/lib/supabase/client";

const profilePhoto=(key:string|null)=>key?`/api/media/profile-photo?key=${encodeURIComponent(key)}`:null;
const relativeTime=(value:string)=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return "Just now";const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes}m`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h`;return `${Math.floor(hours/24)}d`};
const compactCount=(value:number)=>value<1000?String(value):`${Number((value/1000).toFixed(value<10000?1:0))}K`;

export default function GlobalPostPage(){
  const{postId}=useParams<{postId:string}>(),router=useRouter(),{user,profile,loading:profileLoading,authStatus}=useCurrentProfile();
  const[post,setPost]=useState<GlobalPost|null>(null),[loading,setLoading]=useState(true),[comments,setComments]=useState<GlobalComment[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{const next=await loadGlobalPost(postId);setPost(next);if(next){const result=await loadPostComments(next.id);setComments(result.comments)}}catch{setNotice("Post couldn’t load. Try again.")}finally{setLoading(false)}},[postId]);
  useEffect(()=>{if(authStatus==="unauthenticated")router.replace("/login");if(authStatus==="authenticated")void load()},[authStatus,load,router]);
  useEffect(()=>{if(authStatus!=="authenticated")return;const supabase=createClient(),channel=supabase.channel("global-feed-interactions").on("postgres_changes",{event:"*",schema:"public",table:"fc_posts"},payload=>{const id=String(((payload.new as {id?:string}).id??(payload.old as {id?:string}).id)??"");if(id===postId)void load()}).on("postgres_changes",{event:"*",schema:"public",table:"fc_post_likes"},payload=>{const id=String(((payload.new as {post_id?:string}).post_id??(payload.old as {post_id?:string}).post_id)??"");if(id===postId)void load()}).on("postgres_changes",{event:"*",schema:"public",table:"fc_post_comments"},payload=>{const id=String(((payload.new as {post_id?:string}).post_id??(payload.old as {post_id?:string}).post_id)??"");if(id===postId)void load()}).subscribe();return()=>{void supabase.removeChannel(channel)}},[authStatus,load,postId]);
  if(profileLoading||authStatus==="loading"||loading)return <FlirtschatLoader message="Getting things ready..." variant="page"/>;
  if(!user||!profile||!post)return <main className="fc-global-feed-page"><DesktopSidebar mobileOpen={false} onClose={()=>{}} active="global"/><div className="fc-global-feed-shell"><section className="fc-global-feed-state"><strong>Post unavailable</strong><Link href="/global">Back to Global</Link></section></div><AppBottomNav active="global"/></main>;
  const heart=async()=>{if(busy)return;const previous=post,next=!previous.heartedByMe;setBusy(true);setPost({...previous,heartedByMe:next,heartCount:Math.max(0,previous.heartCount+(next?1:-1))});try{const result=await togglePostHeart(post.id);setPost(current=>current?{...current,heartedByMe:result.hearted,heartCount:result.heartCount}:current)}catch{setPost(previous);setNotice("Couldn’t update your heart. Try again.")}finally{setBusy(false)}};
  const save=async()=>{if(busy)return;setBusy(true);try{setPost(current=>current?{...current,savedByMe:!current.savedByMe}:current);const saved=await togglePostSave(post.id);setPost(current=>current?{...current,savedByMe:saved}:current)}catch{setPost(current=>current?{...current,savedByMe:post.savedByMe}:current);setNotice("Couldn’t update your saved posts. Try again.")}finally{setBusy(false)}};
  const share=async()=>{const url=`${window.location.origin}/global/post/${post.id}`;try{if(navigator.share)await navigator.share({title:"FLIRTSCHAT post",text:post.body||"See this post on FLIRTSCHAT",url});else await navigator.clipboard.writeText(url);const count=await recordPostShare(post.id);setPost(current=>current?{...current,shareCount:count}:current)}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setNotice("Couldn’t share this post. Try again.")}};
  const removeComment=async(item:GlobalComment)=>{try{await deletePostComment(item.id);setComments(current=>current.filter(commentRow=>commentRow.id!==item.id));setPost(current=>current?{...current,commentCount:Math.max(0,current.commentCount-1)}:current)}catch{setNotice("Comment couldn’t be deleted. Try again.")}};
  return <main className="fc-global-feed-page"><DesktopSidebar mobileOpen={false} onClose={()=>{}} active="global"/><div className="fc-global-feed-shell fc-global-detail-shell"><Link className="fc-global-detail-back" href="/global"><ArrowLeft/>Back to Global</Link><article className="fc-global-post-card"><header><Link href={`/profile/${post.userId}`} className="fc-global-post-author"><ProfileImage src={profilePhoto(post.photoKey)} alt={post.name}/><span><strong>{post.name}{post.verified&&<b aria-label="Verified">✓</b>}</strong><small>{post.username?`@${post.username}`:"Flirtschat member"} · {relativeTime(post.createdAt)}</small></span></Link></header>{post.body&&<div className="fc-global-post-copy"><p>{post.body}</p></div>}{post.imageKey&&<img className="fc-global-post-image" src={postImageUrl(post.imageKey)} alt={post.body||"Shared post image"} loading="lazy"/>}<div className="fc-global-post-actions"><div className="fc-global-post-actions-left"><button type="button" className={post.heartedByMe?"hearted":""} onClick={()=>void heart()} disabled={busy} aria-label={post.heartedByMe?"Remove heart":"Heart post"} aria-pressed={post.heartedByMe}><Heart fill={post.heartedByMe?"currentColor":"none"}/><span>{compactCount(post.heartCount)}</span></button><button type="button" onClick={()=>document.getElementById("global-detail-comment")?.focus()} aria-label="View comments"><MessageCircle/><span>{compactCount(post.commentCount)}</span></button><button type="button" onClick={()=>void share()} aria-label="Share post"><Share2/><span>{compactCount(post.shareCount)}</span></button></div><button type="button" className={post.savedByMe?"saved":""} onClick={()=>void save()} disabled={busy} aria-label={post.savedByMe?"Remove saved post":"Save post"} aria-pressed={post.savedByMe}><Bookmark fill={post.savedByMe?"currentColor":"none"}/></button></div><PostComments post={post} comments={comments} more={false} loading={false} onLoadMore={()=>{}} onCreated={item=>{setComments(current=>current.some(existing=>existing.id===item.id)?current:[...current,item]);setPost(current=>current?{...current,commentCount:current.commentCount+1}:current)}} onLoaded={item=>setComments(current=>current.some(existing=>existing.id===item.id)?current:[...current,item])} onDeleted={removeComment} onUpdated={item=>setComments(current=>current.map(existing=>existing.id===item.id?item:existing))} onClose={()=>router.push("/global")}/></article></div><AppBottomNav active="global"/>{notice&&<button className="fc-global-notice" type="button" onClick={()=>setNotice("")}>{notice}</button>}</main>;
}
