"use client";
import {BadgeCheck,Crown,Heart,LoaderCircle,MapPin,Users} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {ProfileImage} from "@/components/profile-image";
import {usePresence} from "@/components/presence/presence-provider";
import {getProfiles} from "@/lib/discover-service";
import {loadGlobalLikeStates,toggleGlobalLike,type GlobalLikeState} from "@/lib/global-like-service";
import {subscribeToPublicProfileUpdates} from "@/lib/public-profile-realtime";
import {createClient} from "@/lib/supabase/client";
type GlobalProfile={id:string;name:string;username?:string|null;age:number;place:string;position:string;tag:string;likes:number;verified:boolean;premium:boolean;isNew:boolean;online:boolean;lastSeen:string|null;size:"short"|"medium"|"tall";bio:string;interests:string[];goal:string;languages:string[];photoUrl?:string|null};
const compactLikes=(value:number)=>value<1000?String(value):`${Number((value/1000).toFixed(1))}K`;

export function GlobalProfileGrid({filter="For you",query="",verifiedOnly=false,minLikes=0}:{filter?:string;query?:string;verifiedOnly?:boolean;minLikes?:number}){
  const[profiles,setProfiles]=useState<GlobalProfile[]>([]),[likeStates,setLikeStates]=useState<Record<string,GlobalLikeState>>({}),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[reload,setReload]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);setLoadError(false);getProfiles("all").then(async rows=>{const next=rows.map((p,index)=>({id:p.id,name:p.name,username:p.username,age:p.age,place:[p.city,p.country].filter(Boolean).join(", "),position:"50% 50%",tag:p.relationshipGoal,likes:0,verified:p.verified,premium:p.premium,isNew:p.isNew,online:false,lastSeen:p.lastSeen,size:index%3===0?"tall":index%3===1?"short":"medium",bio:p.bio,interests:p.interests,goal:p.relationshipGoal,languages:p.languages,photoUrl:p.photos[0]??null} as GlobalProfile));if(!active)return;setProfiles(next);setLikeStates(await loadGlobalLikeStates(next.map(item=>item.id)))}).catch(error=>{if(!active)return;console.error("[dashboard/discovery] profile query failed",{code:typeof error==="object"&&error&&"code"in error?String(error.code):"unknown"});setLoadError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reload]);
  useEffect(()=>subscribeToPublicProfileUpdates(()=>setReload(value=>value+1)),[]);
  useEffect(()=>{const ids=profiles.map(profile=>profile.id);if(!ids.length)return;const supabase=createClient();let active=true;let reconcileTimer:ReturnType<typeof setTimeout>|null=null;const reconcile=()=>{if(reconcileTimer)clearTimeout(reconcileTimer);reconcileTimer=setTimeout(()=>void loadGlobalLikeStates(ids).then(next=>{if(active)setLikeStates(next)}).catch(()=>undefined),250)};const channel=supabase.channel("global-profile-like-counts").on("postgres_changes",{event:"INSERT",schema:"public",table:"fc_profile_like_counts"},payload=>{const row=payload.new as {target_id:string;like_count:number|string};if(!active||!ids.includes(row.target_id))return;setLikeStates(current=>{const previous=current[row.target_id]??{likeCount:0,likedByMe:false};return{...current,[row.target_id]:{...previous,likeCount:Math.max(0,Number(row.like_count)||0)}}})}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"fc_profile_like_counts"},payload=>{const row=payload.new as {target_id:string;like_count:number|string};if(!active||!ids.includes(row.target_id))return;setLikeStates(current=>{const previous=current[row.target_id]??{likeCount:0,likedByMe:false};return{...current,[row.target_id]:{...previous,likeCount:Math.max(0,Number(row.like_count)||0)}}})}).on("postgres_changes",{event:"DELETE",schema:"public",table:"fc_profile_like_counts"},payload=>{const row=payload.old as {target_id:string};if(!active||!ids.includes(row.target_id))return;setLikeStates(current=>{const previous=current[row.target_id]??{likeCount:0,likedByMe:false};return{...current,[row.target_id]:{...previous,likeCount:0}}})}).subscribe((status)=>{if(status==="CHANNEL_ERROR"||status==="TIMED_OUT")reconcile()});const online=()=>reconcile();window.addEventListener("online",online);return()=>{active=false;if(reconcileTimer)clearTimeout(reconcileTimer);window.removeEventListener("online",online);void supabase.removeChannel(channel)}},[profiles]);
  const visible=useMemo(()=>{const needle=query.trim().toLowerCase().replace(/^@/,"");let result=profiles.filter(person=>(!verifiedOnly||person.verified)&&(likeStates[person.id]?.likeCount??0)>=minLikes&&`${person.name} ${person.username??""} ${person.place} ${person.tag}`.toLowerCase().includes(needle));if(filter==="Nearby")result=result.slice(0,4);if(filter==="New")result=result.filter(person=>person.isNew);if(filter==="Popular")result=[...result].sort((a,b)=>(likeStates[b.id]?.likeCount??0)-(likeStates[a.id]?.likeCount??0));return result},[filter,likeStates,minLikes,profiles,query,verifiedOnly]);
  if(loading)return <section className="global-feed"><div className="global-masonry">{Array.from({length:4},(_,i)=><div className="global-profile-card medium" key={i}/>)}</div></section>;
  if(loadError)return <section className="global-feed"><div className="global-no-results"><Users/><strong>Profiles couldn&apos;t load</strong><span>Check your connection and try again.</span><button type="button" onClick={()=>setReload(value=>value+1)}><LoaderCircle/>Retry</button></div></section>;
  return <section className="global-feed" id="global-feed">{visible.length?<div className="global-masonry">{visible.map(person=><DashboardProfileCard person={person} likeState={likeStates[person.id]??{likeCount:0,likedByMe:false}} onLikeState={next=>setLikeStates(current=>({...current,[person.id]:next}))} key={person.id}/>)}</div>:<div className="global-no-results"><Users/><strong>No profiles yet</strong><span>New people will appear here as they complete their profiles.</span></div>}</section>;
}
function DashboardProfileCard({person,likeState,onLikeState}:{person:GlobalProfile;likeState:GlobalLikeState;onLikeState:(state:GlobalLikeState)=>void}){const presence=usePresence(person.id,person.lastSeen);return <article className={`global-profile-card ${person.size}`}>{person.isNew&&<span className="global-new-badge">NEW</span>}<span className={`global-card-presence ${presence.online?"online":"offline"}`} aria-label={presence.online?"Online now":presence.label}/>{person.premium&&<span className="global-premium-crown" aria-label="Premium member"><Crown/></span>}<a href={`/profile/${person.id}`} aria-label={`Open ${person.name}'s profile`}><ProfileImage src={person.photoUrl||null} alt={person.name}/><i/></a><LoveButton id={person.id} name={person.name} state={likeState} onState={onLikeState}/><div><h3>{person.name}, {person.age}{person.verified&&<BadgeCheck/>}</h3>{person.username&&<small>@{person.username}</small>}<p><MapPin/>{person.place||"Location not added"}</p></div></article>}
function LoveButton({id,name,state,onState}:{id:string;name:string;state:GlobalLikeState;onState:(state:GlobalLikeState)=>void}){const[busy,setBusy]=useState(false);const toggle=async()=>{if(busy)return;const next=!state.likedByMe;setBusy(true);onState({likedByMe:next,likeCount:Math.max(0,state.likeCount+(next?1:-1))});try{await toggleGlobalLike(id,state.likedByMe)}catch{onState(state)}finally{setBusy(false)}};return <button type="button" className={state.likedByMe?"loved":""} onClick={()=>void toggle()} disabled={busy} aria-pressed={state.likedByMe} aria-label={`${state.likedByMe?"Remove like from":"Like"} ${name}`}><Heart/><b>{compactLikes(state.likeCount)}</b></button>}
