"use client";
import {BadgeCheck,Crown,Heart,MapPin,Users} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {ProfileImage} from "@/components/profile-image";
import {BLOCKED_USERS_EVENT,isProfileBlocked} from "@/lib/blocked-users-service";
import {globalProfiles} from "@/lib/global-profiles";
import {useProfileLike} from "@/lib/use-profile-like";
const compactLikes=(value:number)=>value<1000?String(value):`${Number((value/1000).toFixed(1))}K`;
export function GlobalProfileGrid({filter="For you",query="",verifiedOnly=false,minLikes=0}:{filter?:string;query?:string;verifiedOnly?:boolean;minLikes?:number}){
  const [presence,setPresence]=useState<Record<string,boolean>>(()=>Object.fromEntries(globalProfiles.map(person=>[person.id,person.online]))),[blockedVersion,setBlockedVersion]=useState(0);
  useEffect(()=>{let index=0;const ids=globalProfiles.map(person=>person.id);const timer=setInterval(()=>{const id=ids[index%ids.length];setPresence(current=>({...current,[id]:!current[id]}));index+=1},10000);const syncBlocked=()=>setBlockedVersion(value=>value+1);window.addEventListener(BLOCKED_USERS_EVENT,syncBlocked);return()=>{clearInterval(timer);window.removeEventListener(BLOCKED_USERS_EVENT,syncBlocked)}},[]);
  const visible=useMemo(()=>{if(blockedVersion<0)return[];const needle=query.trim().toLowerCase().replace(/^@/,"");let result=globalProfiles.filter(person=>!isProfileBlocked(person.id)&&(!verifiedOnly||person.verified)&&person.likes>=minLikes&&`${person.name} ${person.id.replace("-global","")} ${person.place} ${person.tag}`.toLowerCase().includes(needle));if(filter==="Nearby")result=result.slice(0,4);if(filter==="New")result=result.filter(person=>person.isNew);if(filter==="Popular")result=[...result].sort((a,b)=>b.likes-a.likes);return result},[blockedVersion,filter,minLikes,query,verifiedOnly]);
  return <section className="global-feed" id="global-feed">{visible.length?<div className="global-masonry">{visible.map(person=>{const online=Boolean(presence[person.id]);return <article className={`global-profile-card ${person.size}`} key={person.id}>{person.isNew&&<span className="global-new-badge">NEW</span>}<span className={`global-card-presence ${online?"online":"offline"}`} aria-label={online?"Online now":"Offline"}/>{person.premium&&<span className="global-premium-crown" aria-label="Premium member"><Crown/></span>}<a href={`/profile/${person.id}`} aria-label={`Open ${person.name}'s profile`}><ProfileImage position={person.position}/><i/></a><LoveButton id={person.id} name={person.name} likes={person.likes}/><div><h3>{person.name}, {person.age}{person.verified&&<BadgeCheck/>}</h3><p><MapPin/>{person.place}</p></div></article>})}</div>:<div className="global-no-results"><Users/><strong>No profiles match</strong><span>Change your search or filters to discover more people.</span></div>}</section>
}
function LoveButton({id,name,likes}:{id:string;name:string;likes:number}){const {loved,count,toggle}=useProfileLike(id,likes);return <button type="button" className={loved?"loved":""} onClick={toggle} aria-pressed={loved} aria-label={`${loved?"Remove like from":"Like"} ${name}`}><Heart/><b>{compactLikes(count)}</b></button>}
