import {createClient} from "@/lib/supabase/client";
import type {FlirtschatNotification,NotificationFilter,NotificationType} from "./notification-types";

const systemTypes=new Set(["gift","visitor","match","system","security","premium","connection_accepted"]);
type NotificationRow={id:string;type:string;title:string;body:string|null;href:string|null;read_at:string|null;created_at:string;actor_user_id:string|null;reference_id:string|null};
type ActorRow={id:string;display_name:string|null;username:string|null};
type PhotoRow={user_id:string;object_key:string};
const allowedTypes=new Set<NotificationType>(["likes","super_like","messages","gift","visitor","match","system","security","premium","mentions","connection_accepted"]);
const relativeTime=(value:string)=>{const elapsed=Math.max(0,Date.now()-new Date(value).getTime()),minutes=Math.floor(elapsed/60000);if(minutes<1)return"Just now";if(minutes<60)return`${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours}h ago`;return`${Math.floor(hours/24)}d ago`};
const normalize=(row:NotificationRow,actor?:ActorRow,photo?:PhotoRow):FlirtschatNotification=>{const type=allowedTypes.has(row.type as NotificationType)?row.type as NotificationType:"system",name=actor?.display_name||actor?.username||null,action=type==="messages"?"sent you a message":type==="super_like"?"sent you a Super Like":type==="likes"?"likes you":type==="visitor"?"viewed your profile":type==="gift"?"sent you a gift":type==="match"?"is your new match":type==="connection_accepted"?"accepted your connection request 🎉":null;return{id:row.id,type,title:name&&action?`${name} ${action}`:row.title,description:row.body??"",time:relativeTime(row.created_at),read:Boolean(row.read_at),href:row.href?.startsWith("/")?row.href:"/notifications",actorId:row.actor_user_id,referenceId:row.reference_id,actorName:name,avatarUrl:photo?`/api/media/profile-photo?key=${encodeURIComponent(photo.object_key)}`:null}};

export async function loadNotifications(){const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Unauthorized");const{data,error}=await supabase.from("fc_notifications").select("id,type,title,body,href,read_at,created_at,actor_user_id,reference_id").eq("user_id",user.id).order("created_at",{ascending:false});if(error)throw error;const rows=(data??[]) as NotificationRow[],actorIds=[...new Set(rows.map(row=>row.actor_user_id).filter((id):id is string=>Boolean(id)))];if(!actorIds.length)return rows.map(row=>normalize(row));const[{data:actors,error:actorError},{data:photos,error:photoError}]=await Promise.all([supabase.from("fc_profiles").select("id,display_name,username").in("id",actorIds),supabase.from("fc_profile_photos").select("user_id,object_key").in("user_id",actorIds).eq("moderation_status","approved").order("position")]);if(actorError)throw actorError;if(photoError)throw photoError;const actorMap=new Map((actors??[]).map(row=>[row.id,row as ActorRow])),photoMap=new Map<string,PhotoRow>();(photos??[]).forEach(row=>{if(!photoMap.has(row.user_id))photoMap.set(row.user_id,row as PhotoRow)});return rows.map(row=>normalize(row,row.actor_user_id?actorMap.get(row.actor_user_id):undefined,row.actor_user_id?photoMap.get(row.actor_user_id):undefined))}
export async function markNotificationRead(id:string){const supabase=createClient(),{error}=await supabase.from("fc_notifications").update({read_at:new Date().toISOString()}).eq("id",id);if(error)throw error}
export async function markAllNotificationsRead(){const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Unauthorized");const{error}=await supabase.from("fc_notifications").update({read_at:new Date().toISOString()}).eq("user_id",user.id).is("read_at",null);if(error)throw error}
export async function deleteNotificationRemote(id:string){const supabase=createClient(),{error}=await supabase.from("fc_notifications").delete().eq("id",id);if(error)throw error}
export async function loadUnreadNotificationCount(){const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Unauthorized");const{count,error}=await supabase.from("fc_notifications").select("id",{count:"exact",head:true}).eq("user_id",user.id).is("read_at",null);if(error)throw error;return count??0}
export async function loadNotificationById(id:string){const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Unauthorized");const{data,error}=await supabase.from("fc_notifications").select("id,type,title,body,href,read_at,created_at,actor_user_id,reference_id").eq("id",id).eq("user_id",user.id).maybeSingle();if(error||!data)return null;const row=data as NotificationRow;if(!row.actor_user_id)return normalize(row);const[{data:actor},{data:photo}]=await Promise.all([supabase.from("fc_profiles").select("id,display_name,username").eq("id",row.actor_user_id).maybeSingle(),supabase.from("fc_profile_photos").select("user_id,object_key").eq("user_id",row.actor_user_id).eq("moderation_status","approved").order("position").limit(1).maybeSingle()]);return normalize(row,actor as ActorRow|undefined,photo as PhotoRow|undefined)}
export function filterNotifications(items:FlirtschatNotification[],filter:NotificationFilter){if(filter==="all")return items;if(filter==="system")return items.filter(item=>systemTypes.has(item.type));if(filter==="likes")return items.filter(item=>item.type==="likes"||item.type==="super_like");return items.filter(item=>item.type===filter)}
