"use client";

/* eslint-disable @next/next/no-img-element -- the source is a local object URL */
import {RotateCcw,X,ZoomIn,ZoomOut} from "lucide-react";
import {useEffect,useRef,useState} from "react";

type CropMode="primary"|"gallery";
type Point={x:number;y:number};

export function ProfilePhotoCropModal({file,mode,onCancel,onSave}:{file:File;mode:CropMode;onCancel:()=>void;onSave:(file:File)=>Promise<void>|void}){
  const originalUrl=useRef(URL.createObjectURL(file)),activeUrls=useRef(new Set([originalUrl.current])),image=useRef<HTMLImageElement>(null),canvas=useRef<HTMLCanvasElement>(null),pointers=useRef(new Map<number,Point>()),lastPointer=useRef<Point|null>(null),pinchDistance=useRef<number|null>(null),pinchZoom=useRef(1);
  const[sourceUrl,setSourceUrl]=useState(originalUrl.current);
  const[natural,setNatural]=useState({width:0,height:0}),[zoom,setZoom]=useState(1),[offset,setOffset]=useState<Point>({x:0,y:0}),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const ratio=mode==="primary"?1:natural.width&&natural.height?Math.min(1.5,Math.max(.75,natural.width/natural.height)):1;
  const frameWidth=320,frameHeight=frameWidth/ratio;
  const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
  const getScale=()=>natural.width&&natural.height?Math.max(frameWidth/natural.width,frameHeight/natural.height):1;
  const constrain=(next:Point,nextZoom=zoom)=>{const scale=getScale()*nextZoom,width=natural.width*scale,height=natural.height*scale;return{x:clamp(next.x,-Math.max(0,(width-frameWidth)/2),Math.max(0,(width-frameWidth)/2)),y:clamp(next.y,-Math.max(0,(height-frameHeight)/2),Math.max(0,(height-frameHeight)/2))}};
  const changeZoom=(value:number)=>{const nextZoom=clamp(value,1,3);setZoom(nextZoom);setOffset(current=>constrain(current,nextZoom))};
  useEffect(()=>{let active=true;const normalize=async()=>{try{if(typeof createImageBitmap!=="function")return;const bitmap=await createImageBitmap(file,{imageOrientation:"from-image"});const normalized=document.createElement("canvas");normalized.width=bitmap.width;normalized.height=bitmap.height;normalized.getContext("2d")?.drawImage(bitmap,0,0);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>normalized.toBlob(resolve,"image/png"));if(!blob)throw new Error("Orientation conversion failed");const url=URL.createObjectURL(blob);activeUrls.current.add(url);if(active){setSourceUrl(url);URL.revokeObjectURL(originalUrl.current)}else URL.revokeObjectURL(url)}catch{ /* The browser image decoder remains the fallback. */}};void normalize();return()=>{active=false}},[file]);
  useEffect(()=>()=>{activeUrls.current.forEach(url=>URL.revokeObjectURL(url))},[]);
  useEffect(()=>{const current=image.current;if(!current)return;const loaded=()=>{setNatural({width:current.naturalWidth,height:current.naturalHeight});setOffset({x:0,y:0});setZoom(1)};if(current.complete)loaded();else current.addEventListener("load",loaded);return()=>current.removeEventListener("load",loaded)},[sourceUrl]);
  const reset=()=>{setZoom(1);setOffset({x:0,y:0});setError("")};
  const save=async()=>{if(!natural.width||!natural.height||!image.current){setError("This image could not be prepared. Choose another photo.");return}setSaving(true);setError("");try{const targetHeight=mode==="primary"?1080:ratio>=1?Math.round(Math.min(1600,natural.width)/ratio):Math.min(1600,natural.height),targetWidth=mode==="primary"?1080:ratio>=1?Math.min(1600,natural.width):Math.round(targetHeight*ratio),output=canvas.current??document.createElement("canvas"),scale=getScale()*zoom,drawWidth=natural.width*scale,drawHeight=natural.height*scale,drawX=(frameWidth-drawWidth)/2+offset.x,drawY=(frameHeight-drawHeight)/2+offset.y;output.width=targetWidth;output.height=targetHeight;const context=output.getContext("2d");if(!context)throw new Error("Canvas unavailable");context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";context.clearRect(0,0,targetWidth,targetHeight);context.drawImage(image.current,drawX*targetWidth/frameWidth,drawY*targetHeight/frameHeight,drawWidth*targetWidth/frameWidth,drawHeight*targetHeight/frameHeight);const blob=await new Promise<Blob|null>(resolve=>output.toBlob(resolve,"image/jpeg",.92));if(!blob||blob.size===0)throw new Error("Empty crop");await onSave(new File([blob],file.name.replace(/\.[^.]+$/,".jpg"),{type:"image/jpeg",lastModified:Date.now()}))}catch(cropError){console.error("Profile photo crop failed",cropError);setError("We couldn't prepare this crop. Try again.")}finally{setSaving(false)}};
  const onPointerDown=(event:React.PointerEvent<HTMLDivElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.current.size===1)lastPointer.current={x:event.clientX,y:event.clientY};if(pointers.current.size===2){const values=[...pointers.current.values()];pinchDistance.current=Math.hypot(values[0].x-values[1].x,values[0].y-values[1].y);pinchZoom.current=zoom}};
  const onPointerMove=(event:React.PointerEvent<HTMLDivElement>)=>{if(!pointers.current.has(event.pointerId))return;pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.current.size===2&&pinchDistance.current){const values=[...pointers.current.values()],distance=Math.hypot(values[0].x-values[1].x,values[0].y-values[1].y);changeZoom(pinchZoom.current*distance/pinchDistance.current);return}if(pointers.current.size!==1||!lastPointer.current)return;const previous=lastPointer.current;lastPointer.current={x:event.clientX,y:event.clientY};setOffset(current=>constrain({x:current.x+event.clientX-previous.x,y:current.y+event.clientY-previous.y}))};
  const onPointerUp=(event:React.PointerEvent<HTMLDivElement>)=>{pointers.current.delete(event.pointerId);if(pointers.current.size<2){pinchDistance.current=null;pinchZoom.current=zoom}lastPointer.current=null};
  return <div className="profile-crop-backdrop" role="presentation"><section className="profile-crop-modal" role="dialog" aria-modal="true" aria-labelledby="profile-crop-title"><header><div><h2 id="profile-crop-title">Crop / Adjust photo</h2><p>{mode==="primary"?"Frame your square profile photo.":"Keep the composition that works best."}</p></div><button type="button" onClick={onCancel} disabled={saving} aria-label="Cancel crop"><X/></button></header><div className="profile-crop-stage-wrap"><div className="profile-crop-stage" style={{width:`min(100%,${frameWidth}px)`,aspectRatio:`${ratio}`}} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp} onWheel={event=>{event.preventDefault();changeZoom(zoom+(event.deltaY<0?.1:-.1))}}><img ref={image} src={sourceUrl} alt="Crop preview" draggable={false} style={{width:natural.width?natural.width*getScale()*zoom:undefined,height:natural.height?natural.height*getScale()*zoom:undefined,transform:`translate(calc(-50% + ${offset.x}px),calc(-50% + ${offset.y}px))`}}/><span className={`profile-crop-overlay ${mode}`} aria-hidden="true"/></div></div>{error&&<p className="profile-crop-error" role="alert">{error}</p>}<div className="profile-crop-controls"><button type="button" onClick={()=>changeZoom(zoom-.1)} disabled={saving||zoom<=1} aria-label="Zoom out"><ZoomOut/></button><input type="range" min="1" max="3" step=".01" value={zoom} onChange={event=>changeZoom(Number(event.target.value))} aria-label="Zoom" disabled={saving}/><button type="button" onClick={()=>changeZoom(zoom+.1)} disabled={saving||zoom>=3} aria-label="Zoom in"><ZoomIn/></button></div><div className="profile-crop-actions"><button type="button" onClick={reset} disabled={saving}><RotateCcw/>Reset</button><button type="button" className="primary" onClick={()=>void save()} disabled={saving||!natural.width}>{saving?"PreparingÃ¢â‚¬Â¦":"Save Photo"}</button></div><canvas ref={canvas} className="profile-crop-canvas" aria-hidden="true"/></section></div>;
}


