export type ReportType="Chat"|"Photo"|"Profile";
export type ReportPriority="High"|"Medium"|"Low";
export type ReportStatus="Open"|"In Review"|"Resolved"|"Dismissed";
export type ModReport={id:string;type:ReportType;priority:ReportPriority;status:ReportStatus;reason:string;reported:{id:string;name:string;username:string;initials:string};reporter:string;created:string;summary:string;evidence:string[];warnings:number};
export type Appeal={id:string;user:string;action:string;submitted:string;reason:string;status:"Pending"|"Approved"|"Rejected"};
export type BlockedAdminUser={id:string;name:string;reason:string;blockedAt:string;by:string};
export type ModerationState={reports:ModReport[];appeals:Appeal[];blocked:BlockedAdminUser[]};
const KEY="flirtschat:admin-moderation-v1";
export const initialModerationState:ModerationState={reports:[
 {id:"RPT-2841",type:"Chat",priority:"High",status:"Open",reason:"Harassment",reported:{id:"FC-10912",name:"Ethan Cole",username:"ethan.c",initials:"EC"},reporter:"Maya T.",created:"2 min ago",summary:"Repeated unwanted and threatening messages after the reporter asked the user to stop.",evidence:["You cannot just ignore me forever.","I know where you usually hang out.","Reply now or you will regret it."],warnings:1},
 {id:"RPT-2839",type:"Photo",priority:"High",status:"In Review",reason:"Explicit content",reported:{id:"FC-10887",name:"Alex Morgan",username:"alex.m",initials:"AM"},reporter:"Aria W.",created:"14 min ago",summary:"A public profile photo may contain prohibited explicit imagery.",evidence:["Flagged profile photo #3","Automated confidence: 94%","Uploaded Aug 1, 2026 · 09:18"],warnings:0},
 {id:"RPT-2835",type:"Profile",priority:"Medium",status:"Open",reason:"Impersonation",reported:{id:"FC-10745",name:"Sam Rivera",username:"sam.r",initials:"SR"},reporter:"Verified member",created:"42 min ago",summary:"Profile photos and biography appear copied from a public creator.",evidence:["Possible source identity: @samrivera_official","Name mismatch detected","Two prior identity checks failed"],warnings:2},
 {id:"RPT-2828",type:"Chat",priority:"Medium",status:"Open",reason:"Spam or scam",reported:{id:"FC-10621",name:"Jordan Blake",username:"jordan.b",initials:"JB"},reporter:"Luna D.",created:"1 hour ago",summary:"User repeatedly shared an external payment link with multiple members.",evidence:["Send $50 to verify your profile","External link removed by safety filter","Same message sent to 18 accounts"],warnings:1},
 {id:"RPT-2814",type:"Photo",priority:"Low",status:"Resolved",reason:"Misleading photo",reported:{id:"FC-10418",name:"Chris Lee",username:"chris.l",initials:"CL"},reporter:"Anonymous",created:"Yesterday",summary:"Reported image did not clearly show the account owner.",evidence:["Photo removed by user","Identity re-verification completed"],warnings:0}
],appeals:[{id:"APL-309",user:"Zoe Martin",action:"Account ban",submitted:"18 min ago",reason:"My account was compromised and I have recovered access.",status:"Pending"},{id:"APL-304",user:"Taylor Kim",action:"Photo removal",submitted:"3 hours ago",reason:"The image was incorrectly classified and contains no prohibited content.",status:"Pending"},{id:"APL-298",user:"Jamie Park",action:"7-day suspension",submitted:"Yesterday",reason:"The messages were taken out of context.",status:"Rejected"}],blocked:[{id:"FC-10322",name:"Ryan Scott",reason:"Repeated harassment",blockedAt:"Jul 31, 2026",by:"Maya Chen"},{id:"FC-10281",name:"Morgan Reed",reason:"Payment scam",blockedAt:"Jul 29, 2026",by:"Avery Morgan"}]};
export function loadModerationState(){try{const saved=localStorage.getItem(KEY);return saved?JSON.parse(saved) as ModerationState:initialModerationState}catch{return initialModerationState}}
export function saveModerationState(state:ModerationState){localStorage.setItem(KEY,JSON.stringify(state))}
