export type VerificationKind="ID"|"Selfie";
export type VerificationStatus="Pending"|"Approved"|"Rejected";
export type VerificationRequest={id:string;kind:VerificationKind;status:VerificationStatus;name:string;username:string;initials:string;country:string;submitted:string;document?:string;documentNumber?:string;dob?:string;match:number;risk:"Low"|"Medium"|"High";checks:{label:string;passed:boolean;detail:string}[];decidedAt?:string;decidedBy?:string;note?:string};
const KEY="flirtschat:admin-verification-v1";
export const initialVerificationRequests:VerificationRequest[]=[
 {id:"VER-3108",kind:"ID",status:"Pending",name:"Amelia Hart",username:"amelia.h",initials:"AH",country:"United Kingdom",submitted:"3 min ago",document:"Passport",documentNumber:"•••• 4821",dob:"May 14, 1999",match:97,risk:"Low",checks:[{label:"Document authenticity",passed:true,detail:"Security features detected"},{label:"Face comparison",passed:true,detail:"97% biometric match"},{label:"Age requirement",passed:true,detail:"Age 27 confirmed"}]},
 {id:"VER-3107",kind:"Selfie",status:"Pending",name:"Noah Williams",username:"noah.w",initials:"NW",country:"United States",submitted:"11 min ago",match:92,risk:"Low",checks:[{label:"Liveness check",passed:true,detail:"Natural motion confirmed"},{label:"Profile photo match",passed:true,detail:"92% biometric match"},{label:"Duplicate search",passed:true,detail:"No related accounts"}]},
 {id:"VER-3104",kind:"ID",status:"Pending",name:"Sofia Laurent",username:"sofia.l",initials:"SL",country:"France",submitted:"28 min ago",document:"National ID",documentNumber:"•••• 7719",dob:"September 3, 2002",match:78,risk:"Medium",checks:[{label:"Document authenticity",passed:true,detail:"Document appears genuine"},{label:"Face comparison",passed:false,detail:"78% — manual review needed"},{label:"Age requirement",passed:true,detail:"Age 23 confirmed"}]},
 {id:"VER-3099",kind:"Selfie",status:"Pending",name:"Liam Chen",username:"liam.c",initials:"LC",country:"Canada",submitted:"1 hour ago",match:61,risk:"High",checks:[{label:"Liveness check",passed:false,detail:"Replay indicators detected"},{label:"Profile photo match",passed:false,detail:"61% — below threshold"},{label:"Duplicate search",passed:true,detail:"No related accounts"}]},
 {id:"VER-3092",kind:"ID",status:"Approved",name:"Maya Thompson",username:"maya.t",initials:"MT",country:"United States",submitted:"Today, 9:12 AM",document:"Driver license",documentNumber:"•••• 2048",dob:"January 22, 1998",match:98,risk:"Low",checks:[{label:"Document authenticity",passed:true,detail:"Security features detected"},{label:"Face comparison",passed:true,detail:"98% biometric match"},{label:"Age requirement",passed:true,detail:"Age 28 confirmed"}],decidedAt:"Today, 9:18 AM",decidedBy:"Maya Chen"},
 {id:"VER-3088",kind:"Selfie",status:"Rejected",name:"Oliver Grant",username:"oliver.g",initials:"OG",country:"Australia",submitted:"Yesterday, 4:46 PM",match:54,risk:"High",checks:[{label:"Liveness check",passed:false,detail:"Static image detected"},{label:"Profile photo match",passed:false,detail:"54% — below threshold"}],decidedAt:"Yesterday, 4:51 PM",decidedBy:"Avery Morgan",note:"Liveness check failed"}
];
export function loadVerificationRequests(){try{const value=localStorage.getItem(KEY);return value?JSON.parse(value) as VerificationRequest[]:initialVerificationRequests}catch{return initialVerificationRequests}}
export function saveVerificationRequests(items:VerificationRequest[]){localStorage.setItem(KEY,JSON.stringify(items))}
