export type Plan={id:string;name:string;price:number;interval:"month"|"year";members:number;active:boolean;popular?:boolean;features:string[]};
export type Subscription={id:string;name:string;email:string;initials:string;plan:string;status:"Active"|"Past due"|"Canceled"|"Trial";started:string;renews:string;amount:string};
export type Invoice={id:string;customer:string;date:string;amount:string;method:string;status:"Paid"|"Failed"|"Refunded"};
export type Refund={id:string;customer:string;invoice:string;amount:string;reason:string;requested:string;status:"Pending"|"Approved"|"Declined"};
export type Promotion={id:string;code:string;kind:"Coupon"|"Promo";discount:string;uses:number;limit:number;expires:string;active:boolean};
export type PremiumState={plans:Plan[];subscriptions:Subscription[];invoices:Invoice[];refunds:Refund[];promotions:Promotion[]};
const KEY="flirtschat:admin-premium-v1";
export const initialPremiumState:PremiumState={plans:[{id:"plan-monthly",name:"Premium Monthly",price:14.99,interval:"month",members:8421,active:true,features:["Unlimited likes","See who liked you","Advanced filters","Incognito mode"]},{id:"plan-yearly",name:"Premium Annual",price:99.99,interval:"year",members:12706,active:true,popular:true,features:["Everything in Monthly","44% annual savings","Monthly profile boost","Priority support"]},{id:"plan-student",name:"Premium Student",price:7.99,interval:"month",members:1840,active:true,features:["Premium essentials","Age and school eligibility","One boost per month"]}],subscriptions:[{id:"SUB-84021",name:"Maya Thompson",email:"maya.t@example.com",initials:"MT",plan:"Premium Annual",status:"Active",started:"Jul 28, 2026",renews:"Jul 28, 2027",amount:"$99.99"},{id:"SUB-84018",name:"Ethan Cole",email:"ethan.c@example.com",initials:"EC",plan:"Premium Monthly",status:"Past due",started:"May 3, 2026",renews:"Payment retry Aug 4",amount:"$14.99"},{id:"SUB-84014",name:"Sofia Laurent",email:"sofia.l@example.com",initials:"SL",plan:"Premium Student",status:"Trial",started:"Aug 1, 2026",renews:"Trial ends Aug 8",amount:"$7.99"},{id:"SUB-83991",name:"Noah Williams",email:"noah.w@example.com",initials:"NW",plan:"Premium Monthly",status:"Canceled",started:"Mar 14, 2026",renews:"Ends Aug 14",amount:"$14.99"}],invoices:[{id:"INV-20948",customer:"Maya Thompson",date:"Aug 2, 2026",amount:"$99.99",method:"Visa •••• 4242",status:"Paid"},{id:"INV-20947",customer:"Ethan Cole",date:"Aug 2, 2026",amount:"$14.99",method:"Mastercard •••• 8821",status:"Failed"},{id:"INV-20942",customer:"Luna Davis",date:"Aug 1, 2026",amount:"$14.99",method:"Apple Pay",status:"Paid"},{id:"INV-20938",customer:"Oliver Grant",date:"Jul 31, 2026",amount:"$99.99",method:"Visa •••• 1984",status:"Refunded"}],refunds:[{id:"REF-1142",customer:"Ava Brooks",invoice:"INV-20931",amount:"$99.99",reason:"Accidental annual renewal",requested:"18 min ago",status:"Pending"},{id:"REF-1139",customer:"Lucas Martin",invoice:"INV-20920",amount:"$14.99",reason:"Premium features unavailable",requested:"2 hours ago",status:"Pending"},{id:"REF-1131",customer:"Oliver Grant",invoice:"INV-20938",amount:"$99.99",reason:"Duplicate subscription",requested:"Yesterday",status:"Approved"}],promotions:[{id:"CPN-204",code:"WELCOME25",kind:"Coupon",discount:"25% off",uses:847,limit:2000,expires:"Sep 30, 2026",active:true},{id:"CPN-199",code:"SUMMER40",kind:"Coupon",discount:"40% off",uses:1200,limit:1200,expires:"Aug 15, 2026",active:false},{id:"PRO-88",code:"DATEWEEK",kind:"Promo",discount:"7 days free",uses:328,limit:1000,expires:"Aug 31, 2026",active:true}]};
export function loadPremiumState(){try{const value=localStorage.getItem(KEY);return value?JSON.parse(value) as PremiumState:initialPremiumState}catch{return initialPremiumState}}
export function savePremiumState(value:PremiumState){localStorage.setItem(KEY,JSON.stringify(value))}
