export type AdminUserStatus="Active"|"Suspended"|"Banned";
export type AdminUser={id:string;name:string;username:string;email:string;age:number;country:string;joined:string;lastActive:string;status:AdminUserStatus;verified:boolean;premium:boolean;reports:number;avatar:string;bio:string;logins:{date:string;location:string;ip:string;result:"Success"|"Failed"}[];devices:{name:string;browser:string;location:string;lastActive:string;current?:boolean}[]};

const KEY="flirtschat:admin-users-v1";
export const initialAdminUsers:AdminUser[]=[
 {id:"FC-10482",name:"Maya Thompson",username:"maya.t",email:"maya@example.com",age:25,country:"United States",joined:"Jul 12, 2026",lastActive:"Online now",status:"Active",verified:true,premium:true,reports:0,avatar:"MT",bio:"Designer, traveler, and coffee enthusiast.",logins:[{date:"Today, 9:42 AM",location:"Los Angeles, US",ip:"172.16.4.28",result:"Success"},{date:"Jul 31, 6:18 PM",location:"Los Angeles, US",ip:"172.16.4.28",result:"Success"}],devices:[{name:"iPhone 16 Pro",browser:"Flirtschat iOS 1.0",location:"Los Angeles, US",lastActive:"Active now",current:true},{name:"MacBook Pro",browser:"Chrome 127 · macOS",location:"Los Angeles, US",lastActive:"2 days ago"}]},
 {id:"FC-10481",name:"Aria Wilson",username:"aria.w",email:"aria@example.com",age:27,country:"Canada",joined:"Jul 11, 2026",lastActive:"4 min ago",status:"Active",verified:true,premium:false,reports:1,avatar:"AW",bio:"Music, books, and spontaneous road trips.",logins:[{date:"Today, 9:31 AM",location:"Toronto, CA",ip:"10.24.8.15",result:"Success"}],devices:[{name:"Pixel 10",browser:"Flirtschat Android 1.0",location:"Toronto, CA",lastActive:"4 min ago",current:true}]},
 {id:"FC-10479",name:"Ivy Anderson",username:"ivy.a",email:"ivy@example.com",age:23,country:"Australia",joined:"Jul 9, 2026",lastActive:"18 min ago",status:"Suspended",verified:false,premium:true,reports:3,avatar:"IA",bio:"Ocean lover and amateur photographer.",logins:[{date:"Today, 8:55 AM",location:"Sydney, AU",ip:"192.168.12.9",result:"Success"},{date:"Jul 30, 2:11 AM",location:"Unknown",ip:"45.18.9.77",result:"Failed"}],devices:[{name:"iPhone 15",browser:"Safari · iOS",location:"Sydney, AU",lastActive:"18 min ago",current:true}]},
 {id:"FC-10472",name:"Luna Davis",username:"luna.d",email:"luna@example.com",age:26,country:"United Kingdom",joined:"Jul 6, 2026",lastActive:"1 hour ago",status:"Active",verified:true,premium:true,reports:0,avatar:"LD",bio:"Creative director. Museums and late-night jazz.",logins:[{date:"Today, 7:44 AM",location:"London, UK",ip:"172.20.10.3",result:"Success"}],devices:[{name:"Galaxy S26",browser:"Flirtschat Android 1.0",location:"London, UK",lastActive:"1 hour ago",current:true}]},
 {id:"FC-10465",name:"Zoe Martin",username:"zoe.m",email:"zoe@example.com",age:24,country:"France",joined:"Jul 2, 2026",lastActive:"Yesterday",status:"Banned",verified:false,premium:false,reports:7,avatar:"ZM",bio:"Food, art, and weekend escapes.",logins:[{date:"Jul 29, 11:03 PM",location:"Paris, FR",ip:"10.0.18.22",result:"Failed"}],devices:[{name:"Windows PC",browser:"Firefox 128 · Windows",location:"Paris, FR",lastActive:"3 days ago"}]},
 {id:"FC-10451",name:"Leo Fischer",username:"leo.f",email:"leo@example.com",age:27,country:"Germany",joined:"Jun 28, 2026",lastActive:"2 days ago",status:"Active",verified:true,premium:false,reports:0,avatar:"LF",bio:"Engineer, cyclist, and home cook.",logins:[{date:"Jul 30, 4:26 PM",location:"Berlin, DE",ip:"192.168.4.12",result:"Success"}],devices:[{name:"MacBook Air",browser:"Chrome 127 · macOS",location:"Berlin, DE",lastActive:"2 days ago",current:true}]},
];
export function loadAdminUsers(){try{const saved=localStorage.getItem(KEY);return saved?JSON.parse(saved) as AdminUser[]:initialAdminUsers}catch{return initialAdminUsers}}
export function saveAdminUsers(users:AdminUser[]){localStorage.setItem(KEY,JSON.stringify(users))}
