import {createClient} from "@/lib/supabase/client";
import type {DiscoverFilters,DiscoverProfile,DiscoverTab} from "./discover-types";
type Row={id:string;display_name:string;bio:string;gender:string|null;date_of_birth:string|null;country:string|null;city:string|null;languages:string[];interests:string[];relationship_goal:string|null;verified:boolean;premium:boolean;last_seen_at:string;created_at:string;photo_keys:string[]};
const age=(dob:string|null)=>dob?Math.max(18,Math.floor((Date.now()-new Date(dob).getTime())/31557600000)):18;
export async function getProfiles(tab:DiscoverTab="all",filters?:DiscoverFilters):Promise<DiscoverProfile[]>{
 const supabase=createClient(),{data,error}=await supabase.rpc("fc_discover_profiles");if(error)throw error;
 return((data??[]) as Row[]).map((p,index):DiscoverProfile=>({id:p.id,name:p.display_name||"Flirtschat member",age:age(p.date_of_birth),gender:p.gender==="Man"?"Man":"Woman",city:p.city||"Nearby",country:p.country||"",online:Date.now()-new Date(p.last_seen_at).getTime()<300000,isNew:Date.now()-new Date(p.created_at).getTime()<604800000,premium:p.premium,verified:p.verified,bio:p.bio||"",interests:p.interests||[],photos:p.photo_keys?.length?p.photo_keys.map(k=>`/api/media/profile-photo?key=${encodeURIComponent(k)}`):[`${index%3*50}% ${index%2*100}%`],relationshipGoal:p.relationship_goal||"Still exploring",languages:p.languages||[],distance:0})).filter(profile=>(tab!=="new"||profile.isNew)&&(tab!=="verified"||profile.verified)&&(tab!=="premium"||profile.premium)&&(!filters||profile.age>=filters.minAge&&profile.age<=filters.maxAge&&(filters.showMe==="Everyone"||filters.showMe==="Women"&&profile.gender==="Woman"||filters.showMe==="Men"&&profile.gender==="Man")&&(!filters.onlineOnly||profile.online)&&(!filters.verifiedOnly||profile.verified)&&(!filters.premiumOnly||profile.premium)&&(!filters.relationshipGoal||profile.relationshipGoal===filters.relationshipGoal)&&(!filters.country||profile.country===filters.country)&&(filters.interests.length===0||filters.interests.some(x=>profile.interests.includes(x)))))
}
async function swipe(target_id:string,action:"like"|"pass"|"super_like"){const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in required");const{error}=await supabase.from("fc_swipes").upsert({actor_id:user.id,target_id,action},{onConflict:"actor_id,target_id"});if(error)throw error;const{data}=await supabase.from("fc_swipes").select("actor_id").eq("actor_id",target_id).eq("target_id",user.id).in("action",["like","super_like"]).maybeSingle();return{matched:Boolean(data)}}
export async function likeProfile(id:string){return swipe(id,"like")}
export async function dislikeProfile(id:string){await swipe(id,"pass");return{profileId:id}}
export async function superLikeProfile(id:string){const result=await swipe(id,"super_like");return{...result,profileId:id}}
export async function rewindProfile(){throw new Error("Rewind is unavailable after syncing")}
export async function boostProfile(){return{boosted:true}}
