export type GlobalProfile={id:string;name:string;age:number;place:string;position:string;tag:string;likes:number;verified:boolean;premium:boolean;isNew:boolean;online:boolean;size:"short"|"medium"|"tall";bio:string;interests:string[];goal:string;languages:string[];photoUrl?:string|null;occupation?:string;education?:string};
export const globalProfiles:GlobalProfile[]=[
  {id:"maya-global",name:"Maya",age:25,place:"Los Angeles",position:"0% 0%",tag:"Golden hour",likes:128,verified:true,premium:true,isNew:true,online:true,size:"tall",bio:"Sunset chaser, ramen enthusiast and always planning a spontaneous little adventure.",interests:["Travel","Photography","Food"],goal:"Serious relationship",languages:["English","Spanish"]},
  {id:"aria-global",name:"Aria",age:27,place:"Santa Monica",position:"50% 0%",tag:"Live music",likes:1094,verified:true,premium:false,isNew:true,online:true,size:"short",bio:"Designer by day, live-music regular by night. Tell me your favorite hidden gem.",interests:["Music","Fashion","Pets"],goal:"Still exploring",languages:["English","French"]},
  {id:"noah-global",name:"Noah",age:29,place:"Pasadena",position:"100% 0%",tag:"Coffee dates",likes:76,verified:false,premium:true,isNew:false,online:false,size:"medium",bio:"Making good coffee, questionable playlists and memories worth keeping.",interests:["Fitness","Technology","Gaming"],goal:"Fun & casual",languages:["English"]},
  {id:"zoe-global",name:"Zoe",age:24,place:"Long Beach",position:"0% 100%",tag:"Ocean energy",likes:1500,verified:true,premium:false,isNew:false,online:true,size:"tall",bio:"Ocean air, old movies and dogs with big personalities.",interests:["Movies","Pets","Food"],goal:"Make friends",languages:["English","Mandarin"]},
  {id:"luna-global",name:"Luna",age:26,place:"West Hollywood",position:"50% 100%",tag:"Night drives",likes:1200,verified:true,premium:true,isNew:true,online:false,size:"medium",bio:"Creative nights, honest conversations and finding magic in ordinary places.",interests:["Art","Music","Fashion"],goal:"Serious relationship",languages:["English","Italian"]},
  {id:"liam-global",name:"Liam",age:28,place:"Burbank",position:"100% 100%",tag:"Weekend hikes",likes:987,verified:false,premium:false,isNew:false,online:false,size:"short",bio:"Usually outdoors, occasionally cooking, always down for a great conversation.",interests:["Hiking","Fitness","Food"],goal:"Still exploring",languages:["English"]},
  {id:"ivy-global",name:"Ivy",age:23,place:"Venice",position:"50% 0%",tag:"Art & ramen",likes:2147,verified:true,premium:true,isNew:true,online:true,size:"tall",bio:"Painting, finding tiny restaurants and collecting stories from new people.",interests:["Art","Food","Travel"],goal:"Serious relationship",languages:["English","Korean"]},
  {id:"leo-global",name:"Leo",age:27,place:"Silver Lake",position:"100% 0%",tag:"Vinyl lover",likes:102,verified:true,premium:false,isNew:false,online:false,size:"medium",bio:"Vinyl on Sundays, good cinema and conversations that run past midnight.",interests:["Music","Movies","Technology"],goal:"Fun & casual",languages:["English","Portuguese"]},
];
