import type {SupabaseClient,User} from "@supabase/supabase-js";
import {createClient} from "@/lib/supabase/server";
import type {CurrentProfile,CurrentProfileUpdate,ProfilePhoto} from "@/lib/profile-types";

const columns="id,username,display_name,bio,gender,interested_in,date_of_birth,country,city,languages,interests,relationship_goal,occupation,education,height_cm,zodiac,exercise,drinking,smoking,pronouns,children,beliefs,min_age,max_age,max_distance,show_me,notifications_enabled,location_permission,profile_visible,onboarding_completed,verified,premium,last_seen_at,created_at,updated_at,suspended_until,profile_banner_dismissed_at";
const development=process.env.NODE_ENV==="development";
const masked=(id:string)=>`${id.slice(0,6)}…${id.slice(-4)}`;
function log(message:string,userId:string,details?:Record<string,unknown>){if(development)console.info(`[profile] ${message}`,{userId:masked(userId),...details})}
function mediaUrl(key:string|null){return key?`/api/media/profile-photo?key=${encodeURIComponent(key)}`:null}
export async function getProfilePhotos(userId:string,client?:SupabaseClient):Promise<ProfilePhoto[]>{const supabase=client??await createClient();const{data,error}=await supabase.from("fc_profile_photos").select("id,object_key,position,moderation_status,created_at").eq("user_id",userId).order("position");if(error){console.error("[profile photo lookup]",{code:error.code,message:error.message,details:error.details,hint:error.hint});throw error}return(data??[]).map(photo=>({id:photo.id,objectKey:photo.object_key,url:mediaUrl(photo.object_key)!,position:photo.position,status:photo.moderation_status,createdAt:photo.created_at}))}
export async function getPrimaryProfilePhoto(userId:string,client?:SupabaseClient){return(await getProfilePhotos(userId,client))[0]?.objectKey??null}
async function normalize(row:Record<string,unknown>,client:SupabaseClient):Promise<CurrentProfile>{const photos=await getProfilePhotos(String(row.id),client),primary=photos[0]??null;return{id:String(row.id),displayName:String(row.display_name??""),username:String(row.username??""),bio:String(row.bio??""),gender:String(row.gender??""),interestedIn:String(row.interested_in??""),dateOfBirth:String(row.date_of_birth??""),country:String(row.country??""),city:String(row.city??""),languages:Array.isArray(row.languages)?row.languages.map(String):[],interests:Array.isArray(row.interests)?row.interests.map(String):[],relationshipGoal:String(row.relationship_goal??""),occupation:String(row.occupation??""),education:String(row.education??""),heightCm:row.height_cm===null||row.height_cm===undefined?null:Number(row.height_cm),zodiac:String(row.zodiac??""),exercise:String(row.exercise??""),drinking:String(row.drinking??""),smoking:String(row.smoking??""),pronouns:String(row.pronouns??""),children:String(row.children??""),beliefs:String(row.beliefs??""),minAge:Number(row.min_age??18),maxAge:Number(row.max_age??35),maxDistance:Number(row.max_distance??50),showMe:(row.show_me??"Everyone") as CurrentProfile["showMe"],notificationsEnabled:Boolean(row.notifications_enabled),locationPermission:Boolean(row.location_permission),profileVisible:Boolean(row.profile_visible),onboardingCompleted:Boolean(row.onboarding_completed),verified:Boolean(row.verified),premium:Boolean(row.premium),createdAt:String(row.created_at??""),updatedAt:String(row.updated_at??""),profileBannerDismissedAt:row.profile_banner_dismissed_at?String(row.profile_banner_dismissed_at):null,photos,primaryPhotoKey:primary?.objectKey??null,primaryPhotoUrl:primary?.url??null}}
async function authenticated(client?:SupabaseClient){const supabase=client??await createClient();const{data:{user},error}=await supabase.auth.getUser();if(error||!user)throw new Error("UNAUTHENTICATED");log("authenticated user found",user.id);return{supabase,user}}
export async function getProfileByUserId(userId:string,client?:SupabaseClient){const supabase=client??await createClient();const{data,error}=await supabase.from("fc_profiles").select(columns).eq("id",userId).maybeSingle();if(error)throw error;log("profile lookup completed",userId,{found:Boolean(data)});return data?normalize(data as Record<string,unknown>,supabase):null}
export async function getCurrentProfile(){const{supabase,user}=await authenticated();return getProfileByUserId(user.id,supabase)}
export async function getOrCreateCurrentProfile(){const{supabase,user}=await authenticated();const profile=await getProfileByUserId(user.id,supabase)??await createMinimumProfile(user,supabase);return{user,profile}}
export async function createMinimumProfile(user:User,client?:SupabaseClient){const supabase=client??await createClient();const existing=await getProfileByUserId(user.id,supabase);if(existing){log("profile found",user.id);return existing}const metadata=user.user_metadata??{},displayName=[metadata.full_name,metadata.name].find(v=>typeof v==="string"&&v.trim())?.trim().slice(0,100)??"";const{error}=await supabase.from("fc_profiles").upsert({id:user.id,display_name:displayName,onboarding_completed:false},{onConflict:"id",ignoreDuplicates:true});if(error)throw error;log("profile created",user.id);const profile=await getProfileByUserId(user.id,supabase);if(!profile)throw new Error("PROFILE_CREATE_FAILED");return profile}
function databasePayload(payload:CurrentProfileUpdate){const nullable=(value:unknown)=>value===""?null:value;return Object.fromEntries(Object.entries({display_name:payload.displayName,username:payload.username===undefined?undefined:payload.username.trim().toLowerCase(),bio:payload.bio,gender:payload.gender===undefined?undefined:nullable(payload.gender),interested_in:payload.interestedIn===undefined?undefined:nullable(payload.interestedIn),date_of_birth:payload.dateOfBirth===undefined?undefined:nullable(payload.dateOfBirth),country:payload.country===undefined?undefined:nullable(payload.country),city:payload.city===undefined?undefined:nullable(payload.city),languages:payload.languages,interests:payload.interests,relationship_goal:payload.relationshipGoal===undefined?undefined:nullable(payload.relationshipGoal),occupation:payload.occupation===undefined?undefined:nullable(payload.occupation),education:payload.education===undefined?undefined:nullable(payload.education),height_cm:payload.heightCm,zodiac:payload.zodiac===undefined?undefined:nullable(payload.zodiac),exercise:payload.exercise===undefined?undefined:nullable(payload.exercise),drinking:payload.drinking===undefined?undefined:nullable(payload.drinking),smoking:payload.smoking===undefined?undefined:nullable(payload.smoking),pronouns:payload.pronouns===undefined?undefined:nullable(payload.pronouns),children:payload.children===undefined?undefined:nullable(payload.children),beliefs:payload.beliefs===undefined?undefined:nullable(payload.beliefs),min_age:payload.minAge,max_age:payload.maxAge,max_distance:payload.maxDistance,show_me:payload.showMe,notifications_enabled:payload.notificationsEnabled,location_permission:payload.locationPermission,profile_visible:payload.profileVisible,updated_at:new Date().toISOString()}).filter(([,value])=>value!==undefined))}
export async function updateCurrentProfile(payload:CurrentProfileUpdate){const{supabase,user}=await authenticated();const{data,error}=await supabase.from("fc_profiles").update(databasePayload(payload)).eq("id",user.id).select(columns).single();if(error)throw error;const profile=await normalize(data as Record<string,unknown>,supabase);log("profile refresh completed",user.id);return profile}
export async function dismissProfileBanner(){const{supabase,user}=await authenticated();const{error}=await supabase.from("fc_profiles").update({profile_banner_dismissed_at:new Date().toISOString()}).eq("id",user.id);if(error)throw error;const profile=await getProfileByUserId(user.id,supabase);if(!profile)throw new Error("PROFILE_NOT_FOUND");return profile}
export async function completeOnboarding(payload:CurrentProfileUpdate&{photoKeys:string[]}){const{supabase,user}=await authenticated();log("onboarding save started",user.id);const{error}=await supabase.rpc("fc_complete_onboarding",{profile_payload:databasePayload(payload),photo_keys:payload.photoKeys});if(error)throw error;const profile=await getProfileByUserId(user.id,supabase);if(!profile)throw new Error("PROFILE_NOT_FOUND");log("onboarding save completed",user.id);return profile}
export async function refreshCurrentProfile(){const profile=await getCurrentProfile();if(profile)log("profile refresh completed",profile.id);return profile}
