import type {CurrentProfile,CurrentProfileUpdate} from "@/lib/profile-types";
export class ProfileRequestError extends Error{constructor(message:string,public readonly status:number,public readonly code?:string){super(message);this.name="ProfileRequestError"}}
async function request(method:"GET"|"PATCH",payload?:CurrentProfileUpdate){let response:Response;try{response=await fetch("/api/profile/me",{method,headers:payload?{"content-type":"application/json"}:undefined,body:payload?JSON.stringify(payload):undefined,cache:"no-store",credentials:"same-origin"})}catch(error){if(process.env.NODE_ENV==="development")console.info("[AuthTrace] profile request result",{method,status:"network_error",error:error instanceof Error?error.name:"unknown"});throw error}if(process.env.NODE_ENV==="development")console.info("[AuthTrace] profile request result",{method,status:response.status});const result=await response.json().catch(()=>null) as {ok?:boolean;profile?:CurrentProfile;error?:string|{code?:string;message?:string;details?:string;hint?:string}}|null;if(!response.ok||!result?.profile){const apiError=typeof result?.error==="object"&&result.error!==null?result.error:null;const message=typeof result?.error==="string"?result.error:apiError?.message;if(process.env.NODE_ENV==="development")console.error("[profile request] failed",{method,status:response.status,code:apiError?.code??"unknown",message:message??"unknown",details:apiError?.details??null,hint:apiError?.hint??null});throw new ProfileRequestError(message??"We couldn't load your profile.",response.status,apiError?.code)}return result.profile}
export const getCurrentProfile=()=>request("GET");
export const refreshCurrentProfile=()=>request("GET");
export const updateCurrentProfile=(payload:CurrentProfileUpdate)=>request("PATCH",payload);
export async function dismissProfileBanner(){const response=await fetch("/api/profile/me",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({profileBannerDismissed:true}),cache:"no-store"});const result=await response.json().catch(()=>null) as {profile?:CurrentProfile;error?:{message?:string}}|null;if(!response.ok||!result?.profile)throw new ProfileRequestError(result?.error?.message??"We couldn't dismiss this message.",response.status);return result.profile}
export async function createMinimumProfile(){await fetch("/api/auth/destination",{method:"POST",cache:"no-store"});return request("GET")}
export async function completeOnboarding(payload:Record<string,unknown>){const response=await fetch("/api/profile/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {profile?:CurrentProfile;error?:{message:string}};if(!response.ok||!result.profile)throw new Error(result.error?.message??"We couldn't save your profile.");return result.profile}
export async function getProfileByUserId(userId:string){const current=await request("GET");return current.id===userId?current:null}
export async function getPrimaryProfilePhoto(userId:string){return(await getProfileByUserId(userId))?.primaryPhotoUrl??null}
