import type {SupabaseClient,User} from "@supabase/supabase-js";
import {createClient} from "@/lib/supabase/server";
import type {CurrentProfile,CurrentProfileUpdate} from "@/lib/profile-types";

const columns="id,username,display_name,bio,gender,interested_in,date_of_birth,country,city,languages,interests,relationship_goal,min_age,max_age,max_distance,show_me,notifications_enabled,location_permission,profile_visible,onboarding_completed,verified,premium,last_seen_at,created_at,updated_at,suspended_until";
const development=process.env.NODE_ENV==="development";
const masked=(id:string)=>`${id.slice(0,6)}…${id.slice(-4)}`;
function log(message:string,userId:string,details?:Record<string,unknown>){if(development)console.info(`[profile] ${message}`,{userId:masked(userId),...details})}
function mediaUrl(key:string|null){return key?`/api/media/profile-photo?key=${encodeURIComponent(key)}`:null}
export async function getPrimaryProfilePhoto(userId:string,client?:SupabaseClient){const supabase=client??await createClient();const{data,error}=await supabase.from("fc_profile_photos").select("object_key").eq("user_id",userId).order("position").limit(1).maybeSingle();if(error){console.error("[profile photo lookup]",{code:error.code,message:error.message,details:error.details,hint:error.hint});return null}return data?.object_key??null}
async function normalize(row:Record<string,unknown>,client:SupabaseClient):Promise<CurrentProfile>{const key=await getPrimaryProfilePhoto(String(row.id),client);return{id:String(row.id),displayName:String(row.display_name??""),username:String(row.username??""),bio:String(row.bio??""),gender:String(row.gender??""),interestedIn:String(row.interested_in??""),dateOfBirth:String(row.date_of_birth??""),country:String(row.country??""),city:String(row.city??""),languages:Array.isArray(row.languages)?row.languages.map(String):[],interests:Array.isArray(row.interests)?row.interests.map(String):[],relationshipGoal:String(row.relationship_goal??""),occupation:"",education:"",minAge:Number(row.min_age??18),maxAge:Number(row.max_age??35),maxDistance:Number(row.max_distance??50),showMe:(row.show_me??"Everyone") as CurrentProfile["showMe"],notificationsEnabled:Boolean(row.notifications_enabled),locationPermission:Boolean(row.location_permission),profileVisible:Boolean(row.profile_visible),onboardingCompleted:Boolean(row.onboarding_completed),verified:Boolean(row.verified),premium:Boolean(row.premium),createdAt:String(row.created_at??""),updatedAt:String(row.updated_at??""),primaryPhotoKey:key,primaryPhotoUrl:mediaUrl(key)}}
async function authenticated(client?:SupabaseClient){const supabase=client??await createClient();const{data:{user},error}=await supabase.auth.getUser();if(error||!user)throw new Error("UNAUTHENTICATED");log("authenticated user found",user.id);return{supabase,user}}
export async function getProfileByUserId(userId:string,client?:SupabaseClient){const supabase=client??await createClient();const{data,error}=await supabase.from("fc_profiles").select(columns).eq("id",userId).maybeSingle();if(error)throw error;log("profile lookup completed",userId,{found:Boolean(data)});return data?normalize(data as Record<string,unknown>,supabase):null}
export async function getCurrentProfile(){const{supabase,user}=await authenticated();return getProfileByUserId(user.id,supabase)}
export async function getOrCreateCurrentProfile(){const{supabase,user}=await authenticated();const profile=await getProfileByUserId(user.id,supabase)??await createMinimumProfile(user,supabase);return{user,profile}}
export async function createMinimumProfile(user:User,client?:SupabaseClient){const supabase=client??await createClient();const existing=await getProfileByUserId(user.id,supabase);if(existing){log("profile found",user.id);return existing}const metadata=user.user_metadata??{},displayName=[metadata.full_name,metadata.name].find(v=>typeof v==="string"&&v.trim())?.trim().slice(0,100)??"";const{error}=await supabase.from("fc_profiles").upsert({id:user.id,display_name:displayName,onboarding_completed:false},{onConflict:"id",ignoreDuplicates:true});if(error)throw error;log("profile created",user.id);const profile=await getProfileByUserId(user.id,supabase);if(!profile)throw new Error("PROFILE_CREATE_FAILED");return profile}
function databasePayload(payload:CurrentProfileUpdate){return Object.fromEntries(Object.entries({display_name:payload.displayName,username:payload.username?.trim().toLowerCase(),bio:payload.bio,gender:payload.gender||null,interested_in:payload.interestedIn||null,date_of_birth:payload.dateOfBirth||null,country:payload.country||null,city:payload.city||null,languages:payload.languages,interests:payload.interests,relationship_goal:payload.relationshipGoal||null,min_age:payload.minAge,max_age:payload.maxAge,max_distance:payload.maxDistance,show_me:payload.showMe,notifications_enabled:payload.notificationsEnabled,location_permission:payload.locationPermission,profile_visible:payload.profileVisible,updated_at:new Date().toISOString()}).filter(([,value])=>value!==undefined))}
export async function updateCurrentProfile(payload:CurrentProfileUpdate){const{supabase,user}=await authenticated();const{error}=await supabase.from("fc_profiles").update(databasePayload(payload)).eq("id",user.id);if(error)throw error;const profile=await getProfileByUserId(user.id,supabase);if(!profile)throw new Error("PROFILE_NOT_FOUND");log("profile refresh completed",user.id);return profile}
export async function completeOnboarding(payload:CurrentProfileUpdate&{photoKeys:string[]}){const{supabase,user}=await authenticated();log("onboarding save started",user.id);const{error}=await supabase.rpc("fc_complete_onboarding",{profile_payload:databasePayload(payload),photo_keys:payload.photoKeys});if(error)throw error;const profile=await getProfileByUserId(user.id,supabase);if(!profile)throw new Error("PROFILE_NOT_FOUND");log("onboarding save completed",user.id);return profile}
export async function refreshCurrentProfile(){const profile=await getCurrentProfile();if(profile)log("profile refresh completed",profile.id);return profile}
