import {NextResponse} from "next/server";
import {z} from "zod";
import {dismissProfileBanner,getOrCreateCurrentProfile,updateCurrentProfile} from "@/lib/profile-service-server";
import {getProfileCompletion} from "@/lib/profile-completion";
export const dynamic="force-dynamic";
const patchSchema=z.object({displayName:z.string().trim().min(2).max(100).optional(),username:z.string().trim().toLowerCase().regex(/^[a-z0-9_]{3,24}$/).optional(),bio:z.string().trim().max(300).optional(),gender:z.string().max(40).optional(),interestedIn:z.string().max(80).optional(),dateOfBirth:z.string().optional(),country:z.string().max(80).optional(),city:z.string().max(80).optional(),languages:z.array(z.string().max(60)).max(20).optional(),interests:z.array(z.string().max(60)).max(30).optional(),relationshipGoal:z.string().max(80).optional(),occupation:z.string().trim().max(80).optional(),education:z.string().trim().max(100).optional(),heightCm:z.number().int().min(100).max(250).nullable().optional(),zodiac:z.string().max(30).optional(),exercise:z.string().max(30).optional(),drinking:z.string().max(30).optional(),smoking:z.string().max(30).optional(),pronouns:z.string().max(40).optional(),children:z.string().max(40).optional(),beliefs:z.string().trim().max(100).optional(),minAge:z.number().int().min(18).max(80).optional(),maxAge:z.number().int().min(18).max(80).optional(),maxDistance:z.number().int().min(1).max(200).optional(),showMe:z.enum(["Women","Men","Everyone"]).optional(),notificationsEnabled:z.boolean().optional(),locationPermission:z.boolean().optional(),profileVisible:z.boolean().optional()}).strict();
const failure=(status:number,message:string)=>NextResponse.json({ok:false,error:{message}},{status});
const responsePayload=(profile:Awaited<ReturnType<typeof updateCurrentProfile>>)=>({ok:true,profile:{...profile,avatar_url:profile.primaryPhotoUrl},profileCompletion:getProfileCompletion(profile),profileBannerDismissed:Boolean(profile.profileBannerDismissedAt),needsOnboarding:!profile.onboardingCompleted});
export async function GET(){try{const{user,profile}=await getOrCreateCurrentProfile();return NextResponse.json({...responsePayload(profile),user:{id:user.id,email:user.email??null}},{headers:{"Cache-Control":"private, no-store, max-age=0"}})}catch(error){const unauthorized=error instanceof Error&&error.message==="UNAUTHENTICATED",supabaseError=error as {code?:unknown;message?:unknown;details?:unknown;hint?:unknown};console.error("[GET /api/profile/me]",{code:supabaseError?.code??"unknown",message:supabaseError?.message??(unauthorized?"Unauthenticated":"Profile load failed"),details:supabaseError?.details??null,hint:supabaseError?.hint??null});return unauthorized?NextResponse.json({error:"Unauthorized"},{status:401}):failure(500,"We couldn't load your profile.")}}
export async function PATCH(request:Request){const body=await request.json().catch(()=>null);if(body&&typeof body==="object"&&Object.keys(body).length===1&&body.profileBannerDismissed===true){try{return NextResponse.json(responsePayload(await dismissProfileBanner()))}catch{return failure(500,"We couldn't dismiss this message.")}}const parsed=patchSchema.safeParse(body);if(!parsed.success)return failure(400,"Check your profile details and try again.");try{return NextResponse.json(responsePayload(await updateCurrentProfile(parsed.data)))}catch(error){if(process.env.NODE_ENV==="development")console.error("Current profile update failed",{code:typeof error==="object"&&error&&"code" in error?String(error.code):"unknown"});return failure(500,"We couldn't save your profile.")}}
