"use client";

import type {RealtimeChannel,User} from "@supabase/supabase-js";
import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type PresenceValue={online:boolean;lastSeen:string|null};
type WatchedChannel={channel:RealtimeChannel;references:number};
type PresenceContextValue={currentUserId:string|null;statuses:Record<string,PresenceValue>;now:number;watch:(userId:string)=>()=>void};
const PresenceContext=createContext<PresenceContextValue|null>(null);
const HEARTBEAT_MS=30_000;
const topic=(userId:string)=>`presence:user:${userId}`;
const payload=(user:User)=>({user_id:user.id,last_seen:new Date().toISOString(),connected_at:new Date().toISOString(),platform:typeof navigator==="undefined"?"web":/Android|iPhone|iPad/i.test(navigator.userAgent)?"mobile-web":"desktop-web",page:typeof location==="undefined"?"/":location.pathname});

export function PresenceProvider({children}:{children:React.ReactNode}){
  const supabase=useMemo(()=>createClient(),[]),ownChannel=useRef<RealtimeChannel|null>(null),watched=useRef(new Map<string,WatchedChannel>()),heartbeat=useRef<number|null>(null),userRef=useRef<User|null>(null);
  const[currentUserId,setCurrentUserId]=useState<string|null>(null),[statuses,setStatuses]=useState<Record<string,PresenceValue>>({}),[now,setNow]=useState(()=>Date.now());
  const setStatus=useCallback((userId:string,value:PresenceValue)=>setStatuses(current=>{const previous=current[userId];return previous?.online===value.online&&previous?.lastSeen===value.lastSeen?current:{...current,[userId]:value}}),[]);
  const persistHeartbeat=useCallback(()=>{void fetch("/api/presence/heartbeat",{method:"POST",cache:"no-store",keepalive:true}).catch(()=>undefined)},[]);
  const stopHeartbeat=useCallback(()=>{if(heartbeat.current!==null){window.clearInterval(heartbeat.current);heartbeat.current=null}},[]);
  const beat=useCallback(()=>{persistHeartbeat();const user=userRef.current,channel=ownChannel.current;if(user&&channel&&!document.hidden)void channel.track(payload(user));setNow(Date.now())},[persistHeartbeat]);
  const startHeartbeat=useCallback(()=>{stopHeartbeat();beat();heartbeat.current=window.setInterval(beat,HEARTBEAT_MS)},[beat,stopHeartbeat]);
  const leave=useCallback(()=>{stopHeartbeat();const channel=ownChannel.current,user=userRef.current;if(channel){void channel.untrack();void supabase.removeChannel(channel);ownChannel.current=null}if(user){setStatus(user.id,{online:false,lastSeen:new Date().toISOString()})}},[setStatus,stopHeartbeat,supabase]);
  const join=useCallback((user:User)=>{leave();userRef.current=user;setCurrentUserId(user.id);const channel=supabase.channel(topic(user.id),{config:{presence:{key:user.id}}});ownChannel.current=channel;channel.on("presence",{event:"sync"},()=>{const entries=channel.presenceState()[user.id]??[];setStatus(user.id,{online:entries.length>0,lastSeen:new Date().toISOString()})}).subscribe(status=>{if(status==="SUBSCRIBED"&&!document.hidden){void channel.track(payload(user));startHeartbeat()}else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"||status==="CLOSED"){setStatus(user.id,{online:false,lastSeen:new Date().toISOString()});persistHeartbeat()}})},[leave,persistHeartbeat,setStatus,startHeartbeat,supabase]);

  useEffect(()=>{const watchedChannels=watched.current;void supabase.auth.getUser().then(({data})=>{if(data.user)join(data.user)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(session?.user){if(userRef.current?.id!==session.user.id)join(session.user)}else{leave();userRef.current=null;setCurrentUserId(null)}});const visibility=()=>{const user=userRef.current,channel=ownChannel.current;if(!user||!channel)return;if(document.hidden){stopHeartbeat();void channel.untrack();persistHeartbeat()}else{void channel.track(payload(user));startHeartbeat()}};const pageHide=()=>{persistHeartbeat();void ownChannel.current?.untrack()};document.addEventListener("visibilitychange",visibility);window.addEventListener("pagehide",pageHide);return()=>{subscription.unsubscribe();document.removeEventListener("visibilitychange",visibility);window.removeEventListener("pagehide",pageHide);leave();for(const item of watchedChannels.values())void supabase.removeChannel(item.channel);watchedChannels.clear()}},[join,leave,persistHeartbeat,startHeartbeat,stopHeartbeat,supabase]);

  const watch=useCallback((userId:string)=>{if(!userId||userId===userRef.current?.id)return()=>undefined;const existing=watched.current.get(userId);if(existing){existing.references++;return()=>{existing.references=Math.max(0,existing.references-1);if(existing.references===0){void supabase.removeChannel(existing.channel);watched.current.delete(userId)}}}const channel=supabase.channel(topic(userId));const item={channel,references:1};watched.current.set(userId,item);const sync=()=>{const entries=(channel.presenceState()[userId]??[])as Array<{last_seen?:unknown}>,latest=entries.map(entry=>typeof entry.last_seen==="string"?entry.last_seen:null).find(Boolean)??null;setStatus(userId,{online:entries.length>0,lastSeen:entries.length?latest:new Date().toISOString()})};channel.on("presence",{event:"sync"},sync).on("presence",{event:"leave"},()=>setStatus(userId,{online:false,lastSeen:new Date().toISOString()})).subscribe(status=>{if(status==="SUBSCRIBED")sync();else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"||status==="CLOSED")setStatus(userId,{online:false,lastSeen:new Date().toISOString()})});return()=>{item.references=Math.max(0,item.references-1);if(item.references===0){void supabase.removeChannel(channel);watched.current.delete(userId)}}},[setStatus,supabase]);
  const value=useMemo(()=>({currentUserId,statuses,now,watch}),[currentUserId,statuses,now,watch]);
  return <PresenceContext.Provider value={value}>{children}</PresenceContext.Provider>;
}

export function usePresence(userId:string|null|undefined,lastSeen:string|null=null){const context=useContext(PresenceContext);if(!context)throw new Error("usePresence must be used inside PresenceProvider");const{watch,statuses,now}=context;useEffect(()=>userId?watch(userId):undefined,[watch,userId]);const status=userId?statuses[userId]:undefined;return{online:Boolean(status?.online),lastSeen:status?.lastSeen??lastSeen,label:status?.online?"Online now":formatLastSeen(status?.lastSeen??lastSeen,now)}}
export function formatLastSeen(value:string|null|undefined,now=Date.now()){if(!value)return"Offline";const time=new Date(value).getTime();if(!Number.isFinite(time))return"Offline";const minutes=Math.max(0,Math.floor((now-time)/60000));if(minutes<1)return"Last seen just now";if(minutes<60)return`Last seen ${minutes} minute${minutes===1?"":"s"} ago`;const hours=Math.floor(minutes/60);if(hours<24)return`Last seen ${hours} hour${hours===1?"":"s"} ago`;if(hours<48)return"Last seen yesterday";return`Last seen ${new Date(time).toLocaleDateString()}`}
