"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import{ArrowRight,Eye,EyeOff,KeyRound,LoaderCircle,LockKeyhole,ShieldCheck}from"lucide-react";
import{useRouter}from"next/navigation";
import{FormEvent,useEffect,useState}from"react";
import{ADMIN_2FA_CODE,authenticateAdmin,createAdminSession,loadAdminSession,type AdminRole}from"@/lib/admin-auth";

type PendingAdmin={name:string;email:string;password:string;role:AdminRole};

export function AdminLogin(){
  const router=useRouter(),[email,setEmail]=useState("admin@flirtschat.com"),[password,setPassword]=useState("Admin@123"),[show,setShow]=useState(false),[pending,setPending]=useState<PendingAdmin|null>(null),[code,setCode]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{if(loadAdminSession())router.replace("/admin")},[router]);
  const login=(event:FormEvent)=>{event.preventDefault();setError("");const account=authenticateAdmin(email,password);if(!account){setError("Email or password is incorrect.");return}setPending(account);setCode("")};
  const verify=()=>{if(!pending)return;setError("");if(code!==ADMIN_2FA_CODE){setError("The verification code is incorrect.");return}setBusy(true);createAdminSession(pending);window.setTimeout(()=>router.replace("/admin"),450)};
  return <main className="admin-auth-page"><section className="admin-auth-brand"><a href="/">FLIRTSCHAT</a><span>CONTROL CENTER</span><h1>Protecting every<br/><em>connection.</em></h1><p>Secure tools for moderation, member support, and platform operations.</p><div><ShieldCheck/><span><strong>Admin-only access</strong><small>Credentials and two-factor verification required</small></span></div></section><section className="admin-auth-panel"><div className="admin-auth-card">{!pending?<><header><i><LockKeyhole/></i><span><small>ADMIN PORTAL</small><h2>Welcome back</h2><p>Sign in to continue to the control center.</p></span></header>{error&&<div className="admin-auth-error" role="alert">{error}</div>}<form onSubmit={login}><label><span>Email address</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label><span>Password</span><div><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff/>:<Eye/>}</button></div></label><button className="admin-login-submit">Continue securely<ArrowRight/></button></form><aside><strong>Demo access</strong><code>admin@flirtschat.com</code><code>Admin@123</code></aside></>:<><header><i><KeyRound/></i><span><small>TWO-FACTOR AUTHENTICATION</small><h2>Verify it&apos;s you</h2><p>Enter the six-digit code from your authenticator.</p></span></header><div className="admin-code-destination"><ShieldCheck/><span><strong>{pending.name}</strong><small>{pending.role} · {pending.email}</small></span></div>{error&&<div className="admin-auth-error" role="alert">{error}</div>}<label className="admin-code-field"><span>Verification code</span><input autoFocus inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000" onKeyDown={e=>{if(e.key==="Enter")verify()}}/></label><button className="admin-login-submit" disabled={code.length!==6||busy} onClick={verify}>{busy?<LoaderCircle className="spin"/>:<ShieldCheck/>}{busy?"Verifying…":"Verify & sign in"}</button><button className="admin-auth-back" onClick={()=>{setPending(null);setError("")}}>Back to sign in</button><aside><strong>Demo authenticator code</strong><code>{ADMIN_2FA_CODE}</code></aside></>}</div></section></main>
}
