"use client";
import{ArrowLeft,BadgeCheck,Check,CheckCircle2,ChevronRight,Clock3,FileCheck2,History,IdCard,ScanFace,Search,ShieldCheck,ShieldQuestion,UserRoundCheck,X,XCircle}from"lucide-react";
import{useRouter}from"next/navigation";import{useEffect,useMemo,useState}from"react";
import{loadAdminSession}from"@/lib/admin-auth";import{loadVerificationRequests,saveVerificationRequests,type VerificationRequest}from"@/lib/admin-verification";
type View="Pending"|"ID"|"Selfie"|"History";
export function AdminVerification(){
 const router=useRouter(),[items,setItems]=useState<VerificationRequest[]|null>(null),[view,setView]=useState<View>("Pending"),[query,setQuery]=useState(""),[risk,setRisk]=useState("All"),[selected,setSelected]=useState<VerificationRequest|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>{if(!loadAdminSession()){router.replace("/admin/login");return}setItems(loadVerificationRequests())},[router]);
 const visible=useMemo(()=>items?.filter(x=>{const viewMatch=view==="History"?x.status!=="Pending":x.status==="Pending"&&(view==="Pending"||x.kind===view);return viewMatch&&(risk==="All"||x.risk===risk)&&`${x.name} ${x.username} ${x.id}`.toLowerCase().includes(query.toLowerCase())})??[],[items,view,query,risk]);
 const decide=(status:"Approved"|"Rejected")=>{if(!items||!selected)return;const note=status==="Rejected"?(selected.checks.find(x=>!x.passed)?.detail||"Manual review did not pass"):undefined,next={...selected,status,decidedAt:"Just now",decidedBy:"Current admin",note};const updated=items.map(x=>x.id===next.id?next:x);setItems(updated);saveVerificationRequests(updated);setSelected(null);setNotice(`${selected.name}'s ${selected.kind.toLowerCase()} verification was ${status.toLowerCase()}.`);setTimeout(()=>setNotice(""),2600)};
 if(!items)return <main className="admin-loading"><ShieldCheck/><span>Loading verification center…</span></main>;
 const pending=items.filter(x=>x.status==="Pending").length,ids=items.filter(x=>x.status==="Pending"&&x.kind==="ID").length,selfies=pending-ids;
 return <main className="verify-admin-page"><header className="verify-top"><a href="/admin"><ArrowLeft/>Dashboard</a><strong>FLIRTSCHAT <span>TRUST</span></strong><aside><i/><span>Review team online</span></aside></header><div className="verify-shell"><section className="verify-heading"><div><small>TRUST & IDENTITY</small><h1>Verification center</h1><p>Review identity documents and selfie checks to keep the community authentic.</p></div><span><ShieldQuestion/><strong>{pending}</strong><small>Awaiting review</small></span></section><section className="verify-metrics"><Metric icon={Clock3} value={pending} label="Pending queue" tone="amber"/><Metric icon={IdCard} value={ids} label="ID verification" tone="purple"/><Metric icon={ScanFace} value={selfies} label="Selfie verification" tone="pink"/><Metric icon={BadgeCheck} value="96.4%" label="Approval rate" tone="green"/></section><nav className="verify-tabs">{([{v:"Pending",icon:Clock3,n:pending},{v:"ID",icon:IdCard,n:ids},{v:"Selfie",icon:ScanFace,n:selfies},{v:"History",icon:History,n:items.length-pending}] as {v:View;icon:typeof Clock3;n:number}[]).map(({v,icon:Icon,n})=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}><Icon/>{v}{v!=="History"&&<b>{n}</b>}</button>)}</nav><section className="verify-tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, username or request ID…"/></label><select value={risk} onChange={e=>setRisk(e.target.value)}><option>All</option><option>Low</option><option>Medium</option><option>High</option></select></section><section className="verify-list"><header><span>Member</span><span>Method</span><span>Match</span><span>Risk</span><span>{view==="History"?"Decision":"Submitted"}</span><span/></header>{visible.map(item=><article key={item.id} onClick={()=>setSelected(item)}><div className="verify-person"><i>{item.initials}</i><span><strong>{item.name}</strong><small>@{item.username} · {item.id}</small><em>{item.country}</em></span></div><span className={`verify-method ${item.kind.toLowerCase()}`}>{item.kind==="ID"?<IdCard/>:<ScanFace/>}{item.kind}</span><strong className={`verify-score ${item.match<70?"low":item.match<85?"mid":""}`}>{item.match}%</strong><em className={`verify-risk ${item.risk.toLowerCase()}`}><i/>{item.risk}</em><time>{view==="History"?item.status:item.submitted}{view==="History"&&<small>{item.decidedAt}</small>}</time><ChevronRight/></article>)}{!visible.length&&<div className="verify-empty"><UserRoundCheck/><strong>All caught up</strong><small>No verification requests match this view.</small></div>}</section></div>{selected&&<Review item={selected} close={()=>setSelected(null)} approve={()=>decide("Approved")} reject={()=>decide("Rejected")}/>} {notice&&<div className="verify-toast"><Check/>{notice}</div>}</main>
}
function Metric({icon:Icon,value,label,tone}:{icon:typeof Clock3,value:string|number,label:string,tone:string}){return <article><i className={tone}><Icon/></i><span><strong>{value}</strong><small>{label}</small></span></article>}
function Review({item,close,approve,reject}:{item:VerificationRequest;close:()=>void;approve:()=>void;reject:()=>void}){return <div className="verify-backdrop" onClick={close}><aside className="verify-drawer" onClick={e=>e.stopPropagation()}><header><div><small>VERIFICATION REVIEW</small><strong>{item.id}</strong></div><button onClick={close}><X/></button></header><section className="verify-review-person"><i>{item.initials}</i><span><h2>{item.name}</h2><p>@{item.username} · {item.country}</p></span><em className={item.risk.toLowerCase()}>{item.risk} risk</em></section><div className="verify-preview"><section><small>PROFILE PHOTO</small><div className="face-card profile"><ScanFace/><b>{item.initials}</b><span>Profile image</span></div></section><strong><span>{item.match}%</span><small>FACE MATCH</small></strong><section><small>{item.kind==="ID"?"DOCUMENT PHOTO":"LIVE SELFIE"}</small><div className="face-card capture"><FileCheck2/><b>{item.initials}</b><span>{item.kind==="ID"?item.document:"Liveness capture"}</span></div></section></div>{item.kind==="ID"&&<div className="verify-document"><IdCard/><span><small>DOCUMENT</small><strong>{item.document}</strong></span><span><small>NUMBER</small><strong>{item.documentNumber}</strong></span><span><small>DATE OF BIRTH</small><strong>{item.dob}</strong></span></div>}<section className="verify-checks"><header><ShieldCheck/><span><strong>Automated checks</strong><small>{item.checks.filter(x=>x.passed).length} of {item.checks.length} checks passed</small></span></header>{item.checks.map(check=><article key={check.label}>{check.passed?<CheckCircle2/>:<XCircle/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></article>)}</section>{item.status==="Pending"?<footer><button onClick={reject}><X/>Reject verification</button><button onClick={approve}><Check/>Approve verification</button></footer>:<section className={`verify-decision ${item.status.toLowerCase()}`}>{item.status==="Approved"?<BadgeCheck/>:<XCircle/>}<span><strong>{item.status}</strong><small>{item.note||`Reviewed by ${item.decidedBy}`} · {item.decidedAt}</small></span></section>}</aside></div>}
