"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {Check,Search,ShieldCheck} from "lucide-react";import {useCallback,useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";
type Kind="reports"|"photos"|"users"|"gifts"|"coins"|"audit";type Row=Record<string,unknown>;
const definitions={reports:{title:"Reports",table:"fc_reports",select:"id,category,details,status,created_at,reported_id",order:"created_at"},photos:{title:"Photo Moderation",table:"fc_profile_photos",select:"id,user_id,object_key,moderation_status,moderator_notes,created_at",order:"created_at"},users:{title:"Users",table:"fc_profiles",select:"id,username,display_name,verified,premium,suspended_until,created_at",order:"created_at"},gifts:{title:"Gift Catalog",table:"fc_gifts",select:"id,name,emoji,coin_cost,premium_only,active",order:"coin_cost"},coins:{title:"Coin Transactions",table:"fc_coin_transactions",select:"id,user_id,amount,kind,description,created_at",order:"created_at"},audit:{title:"Audit Logs",table:"fc_admin_audit_logs",select:"id,actor_id,action,entity_type,entity_id,created_at",order:"created_at"}} as const;
export function AdminDataPage({kind}:{kind:Kind}){
 const supabase=useMemo(()=>createClient(),[]),db:any=supabase,definition=definitions[kind],[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await db.from(definition.table).select(definition.select).order(definition.order,{ascending:false}).limit(250);if(error)setNotice(error.message);else setRows((data??[]) as Row[]);setLoading(false)},[db,definition]);useEffect(()=>{void load()},[load]);
 const visible=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),act=async(action:()=>PromiseLike<{error:unknown}>,message:string)=>{const{error}=await action();if(error){setNotice(String((error as {message?:string}).message||error));return}setNotice(message);await load()};
 return <main className="admin-live-page"><header><a href="/admin">← Dashboard</a><strong>FLIRTSCHAT ADMIN</strong><span><ShieldCheck/>Server authorized</span></header><div><section className="admin-live-title"><i><ShieldCheck/></i><span><h1>{definition.title}</h1><p>Live Supabase data protected by admin RLS policies.</p></span></section><label className="admin-live-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Filter ${definition.title.toLowerCase()}`}/></label>{loading?<p>Loading…</p>:<section className="admin-live-list">{visible.length?visible.map(row=>{const id=String(row.id);return <article key={id}><span><strong>{String(row.category||row.name||row.display_name||row.action||row.kind||id)}</strong><small>{summarize(row)}</small>{kind==="photos"&&<input value={notes[id]||""} onChange={e=>setNotes({...notes,[id]:e.target.value})} placeholder="Moderator notes"/>}</span>{kind==="reports"&&<><button onClick={()=>void act(()=>supabase.rpc("fc_admin_review_report",{report_id:id,new_status:"resolved"}),"Report resolved")}>Resolve</button><button onClick={()=>void act(()=>supabase.rpc("fc_admin_review_report",{report_id:id,new_status:"dismissed"}),"Report dismissed")}>Dismiss</button></>}{kind==="photos"&&<><button onClick={()=>void act(()=>supabase.rpc("fc_admin_moderate_photo",{photo_id:id,new_status:"approved",notes:notes[id]||null}),"Photo approved")}>Approve</button><button onClick={()=>void act(()=>supabase.rpc("fc_admin_moderate_photo",{photo_id:id,new_status:"rejected",notes:notes[id]||"Rejected by moderator"}),"Photo rejected")}>Reject</button></>}</article>}):<p>No records found.</p>}</section>}</div>{notice&&<div className="community-toast"><Check/>{notice}</div>}</main>
}
function summarize(row:Row){return Object.entries(row).filter(([key])=>key!=="id").slice(0,5).map(([key,value])=>`${key}: ${String(value??"—")}`).join(" · ")}
