"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { loginSchema, type LoginValues } from "@/lib/auth-schema";
import { loginWithEmail, loginWithGoogle } from "@/lib/mock-auth";

function GoogleIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 12.23c0-.71-.06-1.4-.18-2.06H12v3.9h5.38a4.6 4.6 0 0 1-2 3.02v2.53h3.25c1.9-1.75 2.97-4.33 2.97-7.39Z" fill="#4285f4"/><path d="M12 22c2.7 0 4.98-.9 6.63-2.38l-3.25-2.53c-.9.6-2.05.97-3.38.97-2.6 0-4.81-1.76-5.6-4.13H3.04v2.6A10 10 0 0 0 12 22Z" fill="#34a853"/><path d="M6.4 13.93A6 6 0 0 1 6.08 12c0-.67.12-1.32.32-1.93v-2.6H3.04A10 10 0 0 0 2 12c0 1.62.39 3.15 1.04 4.53l3.36-2.6Z" fill="#fbbc05"/><path d="M12 5.94c1.47 0 2.78.5 3.82 1.5l2.88-2.89A9.65 9.65 0 0 0 12 2a10 10 0 0 0-8.96 5.47l3.36 2.6c.79-2.37 3-4.13 5.6-4.13Z" fill="#ea4335"/></svg>}

export function LoginForm({initialNotice=null}:{initialNotice?:string|null}){
  const [showPassword,setShowPassword]=useState(false),[notice,setNotice]=useState<string|null>(initialNotice),[googleLoading,setGoogleLoading]=useState(false);
  const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<LoginValues>({resolver:zodResolver(loginSchema),mode:"onChange",reValidateMode:"onChange",defaultValues:{email:"",password:"",remember:true}});
  const submit=async(values:LoginValues)=>{setNotice(null);try{await loginWithEmail(values)}catch(error){setNotice(error instanceof Error?error.message:"Login failed")}};
  const google=async()=>{if(googleLoading)return;setGoogleLoading(true);setNotice(null);try{await loginWithGoogle()}catch{setNotice("We couldn’t complete Google sign-in. Please try again.")}finally{setGoogleLoading(false)}};
  return <div className="image-login-card"><header className="image-login-brand"><a href="/" aria-label="Flirtschat home">FLIRTSCHAT</a><i/><span>GEN Z DATING</span></header><div className="image-login-heading"><h1>Welcome Back</h1><p>Someone interesting might be waiting for you.</p></div>{notice&&<div className="image-login-error" role="alert">{notice}</div>}<button className="image-google-button" type="button" onClick={google} disabled={googleLoading||isSubmitting}>{googleLoading?<LoaderCircle className="spin"/>:<GoogleIcon/>}<strong>{googleLoading?"Connecting…":"Continue with Google"}</strong></button><div className="image-login-or"><span>OR</span></div><form onSubmit={handleSubmit(submit)} noValidate><div><label className={`image-login-input ${errors.email?"error":""}`}><Mail/><input aria-label="Email or username" placeholder="Email or username" autoComplete="username" {...register("email")}/></label>{errors.email&&<p className="image-field-error">{errors.email.message}</p>}</div><div><label className={`image-login-input ${errors.password?"error":""}`}><LockKeyhole/><input aria-label="Password" type={showPassword?"text":"password"} placeholder="Password" autoComplete="current-password" {...register("password")}/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Hide password":"Show password"}>{showPassword?<EyeOff/>:<Eye/>}</button></label>{errors.password&&<p className="image-field-error">{errors.password.message}</p>}</div><div className="image-login-options"><label><input type="checkbox" {...register("remember")}/><span/><small>Remember me</small></label><a href="/forgot-password">Forgot password?</a></div><button className="image-login-submit" type="submit" disabled={isSubmitting||googleLoading}>{isSubmitting?<><LoaderCircle className="spin"/>Logging in…</>:"Log In"}</button></form><p className="image-login-signup">New here? <a href="/signup">Create account</a></p><footer>© 2026 Flirtschat. Made for Gen Z</footer></div>
}
