"use client";

import {ArrowLeft,Check,Clock3,Search,ShieldCheck,Trash2,Undo2,UserRoundCheck,UserRoundX,X} from "lucide-react";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {ProfileImage} from "@/components/profile-image";
import {BLOCKED_USERS_EVENT,BLOCKED_USERS_KEY,loadBlockedUsers,unblockAllUsers,unblockUser,type BlockedUserRecord} from "@/lib/blocked-users-service";
import {globalProfiles} from "@/lib/global-profiles";

export function BlockedUsersPage(){
  const [records,setRecords]=useState<BlockedUserRecord[]>([]),[query,setQuery]=useState(""),[confirmAll,setConfirmAll]=useState(false),[undo,setUndo]=useState<BlockedUserRecord|null>(null),[notice,setNotice]=useState("");
  useEffect(()=>{const sync=()=>setRecords(loadBlockedUsers());sync();const storage=(event:StorageEvent)=>{if(event.key===BLOCKED_USERS_KEY)sync()};window.addEventListener(BLOCKED_USERS_EVENT,sync);window.addEventListener("storage",storage);return()=>{window.removeEventListener(BLOCKED_USERS_EVENT,sync);window.removeEventListener("storage",storage)}},[]);
  const users=useMemo(()=>records.map(record=>{const normalized=record.profileId.replace(/-global$/i,"");const profile=globalProfiles.find(item=>item.id.replace(/-global$/i,"")===normalized);return{record,profile}}).filter(item=>`${item.profile?.name??item.record.profileId} ${item.profile?.place??""}`.toLowerCase().includes(query.trim().toLowerCase())),[query,records]);
  const remove=(record:BlockedUserRecord)=>{unblockUser(record.profileId);setUndo(record);setNotice("User unblocked");window.setTimeout(()=>{setUndo(null);setNotice("")},5000)};
  const restore=()=>{if(!undo)return;const current=loadBlockedUsers();localStorage.setItem(BLOCKED_USERS_KEY,JSON.stringify([undo,...current]));window.dispatchEvent(new CustomEvent(BLOCKED_USERS_EVENT));setUndo(null);setNotice("Block restored");window.setTimeout(()=>setNotice(""),2200)};
  const clear=()=>{unblockAllUsers();setConfirmAll(false);setNotice("All users unblocked");window.setTimeout(()=>setNotice(""),2200)};
  return <main className="blocked-page"><header className="blocked-header"><Link href="/settings" aria-label="Back to settings"><ArrowLeft/></Link><div><h1>Blocked Users</h1><p>Manage accounts you have blocked</p></div><i><UserRoundX/></i></header><div className="blocked-shell"><section className="blocked-summary"><i><ShieldCheck/></i><span><strong>{records.length} blocked {records.length===1?"account":"accounts"}</strong><small>Blocked people cannot find, message or interact with you.</small></span></section>{records.length>0&&<><label className="blocked-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search blocked users" aria-label="Search blocked users"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Clear search"><X/></button>}</label><div className="blocked-list">{users.map(({record,profile})=><article key={record.profileId}><span className="blocked-avatar"><ProfileImage position={profile?.position??"0% 0%"}/><i><UserRoundX/></i></span><span className="blocked-copy"><strong>{profile?.name??record.profileId.replace(/-global$/i,"")}</strong><small>{profile?.place??"Flirtschat member"}</small><time><Clock3/>{formatDate(record.blockedAt)} · {record.reason}</time></span><button type="button" onClick={()=>remove(record)}><Undo2/>Unblock</button></article>)}{users.length===0&&<p className="blocked-no-result">No blocked users match your search.</p>}</div><button type="button" className="blocked-clear" onClick={()=>setConfirmAll(true)}><Trash2/>Unblock everyone</button></>}{records.length===0&&<section className="blocked-empty"><i><UserRoundCheck/></i><h2>No blocked users</h2><p>Accounts you block will appear here. You can unblock them at any time.</p><Link href="/dashboard">Explore profiles</Link></section>}<p className="blocked-help">Unblocking does not restore previous matches or conversations automatically.</p></div>{confirmAll&&<div className="blocked-dialog-backdrop" role="dialog" aria-modal="true" aria-labelledby="unblock-all-title" onClick={()=>setConfirmAll(false)}><section onClick={event=>event.stopPropagation()}><i><Trash2/></i><h2 id="unblock-all-title">Unblock everyone?</h2><p>All blocked accounts may be able to find and contact you again, depending on your privacy settings.</p><button type="button" onClick={clear}>Yes, unblock all</button><button type="button" onClick={()=>setConfirmAll(false)}>Cancel</button></section></div>}{notice&&<div className="blocked-toast" role="status"><Check/>{notice}{undo&&<button type="button" onClick={restore}>Undo</button>}</div>}<AppBottomNav active="settings"/></main>
}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?"Recently":new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric"}).format(date)}
