"use client";

import {AlertTriangle,ArrowLeft,Check,ChevronRight,Chrome,Clock3,Fingerprint,KeyRound,Laptop,LoaderCircle,LockKeyhole,LogOut,MapPin,MonitorSmartphone,ShieldCheck,Smartphone,Trash2,X} from "lucide-react";
import Link from "next/link";
import {useEffect,useState} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {disableTwoFactor,loadSecurityState,MOCK_2FA_CODE,registerPasskey,removePasskey,revokeOtherSessions,revokeSession,setLoginAlerts,toggleTrustedSession,verifyTwoFactor,type SecurityState} from "@/lib/security-settings-service";

export function LoginSecurityPage(){
  const [state,setState]=useState<SecurityState|null>(null),[busy,setBusy]=useState(""),[twoFactorOpen,setTwoFactorOpen]=useState(false),[code,setCode]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>setState(loadSecurityState()),[]);
  const run=async(id:string,action:()=>Promise<SecurityState>,message:string)=>{if(busy)return;setBusy(id);setError("");try{setState(await action());setNotice(message);setTimeout(()=>setNotice(""),3000)}catch(reason){setError(reason instanceof Error?reason.message:"Security action failed")}finally{setBusy("")}};
  const submitTwoFactor=async()=>{if(busy)return;setBusy("2fa");setError("");try{const next=await verifyTwoFactor(code);setState(next);setTwoFactorOpen(false);setCode("");setNotice("Two-step verification enabled");setTimeout(()=>setNotice(""),3000)}catch(reason){setError(reason instanceof Error?reason.message:"Verification failed")}finally{setBusy("")}};
  if(!state)return <main className="security-loading"><LoaderCircle className="spin"/>Loading security settings…</main>;
  return <main className="security-page">
    <header className="security-header"><Link href="/settings" aria-label="Back to settings"><ArrowLeft/></Link><div><h1>Login & Security</h1><p>Manage access, devices and protection</p></div><span><ShieldCheck/></span></header>
    <div className="security-shell">
      <section className="security-score"><i><ShieldCheck/></i><div><span><strong>Security score</strong><b>{state.twoFactor&&state.passkey?"Excellent":state.twoFactor||state.passkey?"Good":"Needs attention"}</b></span><div><em style={{width:state.twoFactor&&state.passkey?"100%":state.twoFactor||state.passkey?"72%":"46%"}}/></div><small>{state.twoFactor?"Your account has enhanced sign-in protection.":"Enable two-step verification to strengthen your account."}</small></div></section>

      <SecuritySection title="Sign-in protection">
        <SecurityToggle icon={<ShieldCheck/>} accent="violet" title="Two-step verification" detail={state.twoFactor?"Enabled · Authenticator protection active":"Add a verification code after your password"} checked={state.twoFactor} busy={busy==="2fa-off"} onClick={()=>state.twoFactor?void run("2fa-off",disableTwoFactor,"Two-step verification disabled"):setTwoFactorOpen(true)}/>
        <SecurityToggle icon={<AlertTriangle/>} accent="pink" title="Login alerts" detail="Get notified about new or suspicious sign-ins" checked={state.loginAlerts} busy={busy==="alerts"} onClick={()=>void run("alerts",()=>setLoginAlerts(!state.loginAlerts),`Login alerts ${state.loginAlerts?"disabled":"enabled"}`)}/>
        <SecurityAction icon={<Fingerprint/>} accent="cyan" title="Passkey" detail={state.passkey?"Passkey registered on this device":"Use your fingerprint, face or device PIN"} value={state.passkey?"Remove":"Add"} busy={busy==="passkey"} onClick={()=>void run("passkey",state.passkey?removePasskey:registerPasskey,state.passkey?"Passkey removed":"Passkey added to this device")}/>
        <Link className="security-row" href="/settings/password"><i className="security-metal red"><KeyRound/></i><span><strong>Change password</strong><small>Update your account password securely</small></span><ChevronRight/></Link>
      </SecuritySection>

      <section className="security-section"><header><div><h2>Active sessions</h2><p>{state.sessions.length} signed-in {state.sessions.length===1?"device":"devices"}</p></div>{state.sessions.some(session=>!session.current)&&<button onClick={()=>void run("all-sessions",revokeOtherSessions,"All other devices signed out")} disabled={busy==="all-sessions"}>{busy==="all-sessions"?<LoaderCircle className="spin"/>:<LogOut/>}Sign out all</button>}</header><div className="security-session-list">{state.sessions.map(session=><article key={session.id}><i className={`security-device ${session.current?"current":""}`}>{session.device.includes("iPhone")?<Smartphone/>:session.device.includes("Tab")?<MonitorSmartphone/>:<Laptop/>}</i><div><strong>{session.device}{session.current&&<em>Current</em>}</strong><small><Chrome/>{session.browser}</small><small><MapPin/>{session.location}</small><small><Clock3/>{session.lastActive}</small></div><div className="security-session-actions">{!session.current&&<button onClick={()=>void run(`trust-${session.id}`,()=>toggleTrustedSession(session.id),session.trusted?"Device removed from trusted list":"Device marked as trusted")} disabled={busy===`trust-${session.id}`}>{session.trusted?"Trusted":"Trust"}</button>}{!session.current&&<button className="revoke" aria-label={`Sign out ${session.device}`} onClick={()=>void run(`revoke-${session.id}`,()=>revokeSession(session.id),`${session.device} signed out`)} disabled={busy===`revoke-${session.id}`}><Trash2/></button>}</div></article>)}</div></section>

      <section className="security-section"><header><div><h2>Recent security activity</h2><p>Latest account access events</p></div></header><div className="security-activity">{state.activity.map(item=><article key={item.id}><i className={item.safe?"safe":"warning"}>{item.safe?<Check/>:<AlertTriangle/>}</i><span><strong>{item.title}</strong><small>{item.detail}</small></span><time>{item.time}</time></article>)}</div></section>
    </div>
    {twoFactorOpen&&<div className="security-modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="two-factor-title"><section className="security-modal"><button className="security-modal-close" onClick={()=>{setTwoFactorOpen(false);setCode("");setError("")}} aria-label="Close"><X/></button><i className="security-modal-icon"><LockKeyhole/></i><h2 id="two-factor-title">Set up two-step verification</h2><p>Enter the 6-digit code from your authenticator app.</p><div className="security-secret"><span>Demo authenticator code</span><strong>{MOCK_2FA_CODE}</strong></div><input inputMode="numeric" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,"").slice(0,6))} aria-label="Authenticator code" placeholder="000000"/>{error&&<small>{error}</small>}<button className="security-confirm" onClick={()=>void submitTwoFactor()} disabled={code.length!==6||busy==="2fa"}>{busy==="2fa"?<LoaderCircle className="spin"/>:<ShieldCheck/>}Enable protection</button></section></div>}
    {error&&!twoFactorOpen&&<div className="security-toast error" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="security-toast" role="status"><Check/>{notice}</div>}
    <AppBottomNav active="settings"/>
  </main>
}

function SecuritySection({title,children}:{title:string;children:React.ReactNode}){return <section className="security-section"><header><div><h2>{title}</h2><p>Extra layers of account security</p></div></header><div className="security-group">{children}</div></section>}
function SecurityToggle({icon,accent,title,detail,checked,busy,onClick}:{icon:React.ReactNode;accent:string;title:string;detail:string;checked:boolean;busy:boolean;onClick:()=>void}){return <button className="security-row" type="button" onClick={onClick} disabled={busy}><i className={`security-metal ${accent}`}>{icon}</i><span><strong>{title}</strong><small>{detail}</small></span>{busy?<LoaderCircle className="spin"/>:<b className={`security-switch ${checked?"checked":""}`}><em/></b>}</button>}
function SecurityAction({icon,accent,title,detail,value,busy,onClick}:{icon:React.ReactNode;accent:string;title:string;detail:string;value:string;busy:boolean;onClick:()=>void}){return <button className="security-row" type="button" onClick={onClick} disabled={busy}><i className={`security-metal ${accent}`}>{icon}</i><span><strong>{title}</strong><small>{detail}</small></span>{busy?<LoaderCircle className="spin"/>:<b className="security-value">{value}</b>}</button>}
