"use client";

import {ArrowLeft,Cake,Check,CheckCheck,Clock3,Crown,Eye,EyeOff,MapPin,MessageCircle,RotateCcw,Search,Share2,ShieldCheck,Sparkles,Users,Wifi} from "lucide-react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState,type ReactNode} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {FlirtschatLoader} from "@/components/ui/flirtschat-loader";
import {PRIVACY_SETTINGS_EVENT,PRIVACY_SETTINGS_KEY,loadPrivacySettings,resetPrivacySettings,savePrivacySettings,type PrivacyAudience,type PrivacySettings} from "@/lib/privacy-settings";
import {isPremiumUser} from "@/lib/discover-entitlements";

export function PrivacySettingsPage(){
  const router=useRouter();
  const [value,setValue]=useState<PrivacySettings|null>(null);
  const [saved,setSaved]=useState(false);
  const [premium,setPremium]=useState(false);
  useEffect(()=>{const sync=()=>{const active=isPremiumUser();setPremium(active);const stored=loadPrivacySettings();if(!active&&(!stored.showOnlineStatus||!stored.readReceipts)){const enforced={...stored,showOnlineStatus:true,readReceipts:true};savePrivacySettings(enforced);setValue(enforced)}else setValue(stored)};sync();const storage=(event:StorageEvent)=>{if(event.key===PRIVACY_SETTINGS_KEY)sync()};window.addEventListener(PRIVACY_SETTINGS_EVENT,sync);window.addEventListener("flirtschat:premium-change",sync);window.addEventListener("storage",storage);return()=>{window.removeEventListener(PRIVACY_SETTINGS_EVENT,sync);window.removeEventListener("flirtschat:premium-change",sync);window.removeEventListener("storage",storage)}},[]);
  if(!value)return <FlirtschatLoader context="settings"/>;
  const update=<K extends keyof PrivacySettings>(key:K,next:PrivacySettings[K])=>{const updated={...value,[key]:next};setValue(updated);savePrivacySettings(updated);setSaved(true);window.setTimeout(()=>setSaved(false),1800)};
  const requirePremium=()=>router.push("/premium");
  const reset=()=>{setValue(resetPrivacySettings());setSaved(true);window.setTimeout(()=>setSaved(false),1800)};
  return <main className="privacy-page"><header className="privacy-header"><Link href="/settings" aria-label="Back to settings"><ArrowLeft/></Link><div><h1>Privacy Settings</h1><p>Control who can see and contact you</p></div><i><ShieldCheck/></i></header><div className="privacy-shell"><section className="privacy-status"><i>{value.profileVisibility==="nobody"?<EyeOff/>:<Eye/>}</i><span><strong>{value.profileVisibility==="nobody"?"Your profile is hidden":value.profileVisibility==="matches"?"Visible to matches only":"Your profile is visible"}</strong><small>Changes are saved and applied instantly.</small></span><b>Live</b></section>
    <PrivacyCard icon={<Users/>} accent="pink" title="Profile visibility" detail="Choose who can open your profile"><AudienceControl value={value.profileVisibility} options={["everyone","matches","nobody"]} onChange={next=>update("profileVisibility",next)}/></PrivacyCard>
    <PrivacyCard icon={<MessageCircle/>} accent="violet" title="Who can message you" detail="Control new conversation requests"><AudienceControl value={value.messagePermission} options={["everyone","matches"]} onChange={next=>update("messagePermission",next as PrivacySettings["messagePermission"])}/></PrivacyCard>
    <PrivacyCard icon={<Eye/>} accent="blue" title="Activity & profile details" detail="Choose which details other people can see"><div className="privacy-toggles"><PrivacyToggle label="Online status" detail={premium?"Show when you are currently active":"Always on for free members"} value={premium?value.showOnlineStatus:true} onChange={next=>update("showOnlineStatus",next)} icon={<Wifi/>} accent="green" locked={!premium} onLocked={requirePremium}/><PrivacyToggle label="Last active" detail="Show when you were last online" value={value.showLastActive} onChange={next=>update("showLastActive",next)} icon={<Clock3/>} accent="violet"/><PrivacyToggle label="Distance" detail="Show your approximate distance" value={value.showDistance} onChange={next=>update("showDistance",next)} icon={<MapPin/>} accent="pink"/><PrivacyToggle label="Age" detail="Show your age on your profile" value={value.showAge} onChange={next=>update("showAge",next)} icon={<Cake/>} accent="gold"/><PrivacyToggle label="Read receipts" detail={premium?"Let matches know when messages are opened":"Always on for free members"} value={premium?value.readReceipts:true} onChange={next=>update("readReceipts",next)} icon={<CheckCheck/>} accent="cyan" locked={!premium} onLocked={requirePremium}/></div></PrivacyCard>
    <PrivacyCard icon={<Search/>} accent="gold" title="Discovery & sharing" detail="Control how people find your profile"><div className="privacy-toggles"><PrivacyToggle label="Appear in search" detail="Allow people to find your username" value={value.appearInSearch} onChange={next=>update("appearInSearch",next)} icon={<Search/>} accent="blue"/><PrivacyToggle label="Profile sharing" detail="Allow your profile link to be shared" value={value.allowProfileSharing} onChange={next=>update("allowProfileSharing",next)} icon={<Share2/>} accent="pink"/><PrivacyToggle label="Personalized discovery" detail="Use activity to improve recommendations" value={value.personalizedDiscovery} onChange={next=>update("personalizedDiscovery",next)} icon={<Sparkles/>} accent="violet"/></div></PrivacyCard>
    <button type="button" className="privacy-reset" onClick={reset}><RotateCcw/>Restore default privacy</button><p className="privacy-note">Your choices are stored privately on this device for the mock app and are ready to connect to Supabase Row Level Security later.</p></div>{saved&&<div className="privacy-toast" role="status"><Check/>Privacy updated</div>}<AppBottomNav active="settings"/></main>
}
function PrivacyCard({icon,accent,title,detail,children}:{icon:ReactNode;accent:string;title:string;detail:string;children:ReactNode}){return <section className="privacy-card"><header><i className={`privacy-metal-icon ${accent}`}>{icon}</i><span><strong>{title}</strong><small>{detail}</small></span></header>{children}</section>}
function AudienceControl({value,options,onChange}:{value:PrivacyAudience;options:PrivacyAudience[];onChange:(value:PrivacyAudience)=>void}){return <div className="privacy-audience">{options.map(option=><button type="button" className={value===option?"active":""} onClick={()=>onChange(option)} key={option}>{option==="everyone"?"Everyone":option==="matches"?"Matches only":"Nobody"}{value===option&&<Check/>}</button>)}</div>}
function PrivacyToggle({label,detail,value,onChange,icon,accent="green",locked=false,onLocked}:{label:string;detail:string;value:boolean;onChange:(value:boolean)=>void;icon?:ReactNode;accent?:string;locked?:boolean;onLocked?:()=>void}){return <label className={locked?"premium-locked":""} onClick={event=>{if(locked){event.preventDefault();onLocked?.()}}}><span>{icon&&<em className={`privacy-option-icon ${accent}`}>{icon}</em>}<i><strong>{label}{locked&&<b><Crown/>PRO</b>}</strong><small>{detail}</small></i></span><input type="checkbox" checked={value} onChange={event=>{if(!locked)onChange(event.target.checked)}} aria-label={label}/><b><i/></b></label>}
