"use client";
import {ArrowLeft,BadgeCheck,Check,ChevronRight,Clock3,FileWarning,LockKeyhole,MapPin,Phone,Play,ShieldCheck,Square,UserRoundCheck,UserRoundX,X} from "lucide-react";
import Link from "next/link";
import {useEffect,useMemo,useState,type CSSProperties,type ReactNode} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {FlirtschatLoader} from "@/components/ui/flirtschat-loader";
import {SAFETY_STATE_EVENT,SAFETY_STATE_KEY,loadSafetyState,saveSafetyState,type SafetyChecklist,type SafetyState} from "@/lib/safety-center-service";
const checks:[keyof SafetyChecklist,string,string][]=[["meetPublic","Meet in a public place","Choose a busy, familiar location"],["tellFriend","Tell someone your plans","Share who, where and when"],["ownTransport","Plan your own transport","Keep control of how you leave"],["protectDetails","Protect personal details","Avoid sharing your address or finances"],["trustInstincts","Trust your instincts","Leave whenever something feels wrong"]];
export function SafetyCenterPage(){
 const [state,setState]=useState<SafetyState|null>(null),[notice,setNotice]=useState(""),[now,setNow]=useState(Date.now());
 useEffect(()=>{const sync=()=>setState(loadSafetyState());sync();const storage=(event:StorageEvent)=>{if(event.key===SAFETY_STATE_KEY)sync()};window.addEventListener(SAFETY_STATE_EVENT,sync);window.addEventListener("storage",storage);const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>{window.removeEventListener(SAFETY_STATE_EVENT,sync);window.removeEventListener("storage",storage);window.clearInterval(timer)}},[]);
 const score=useMemo(()=>state?Math.round(Object.values(state.checklist).filter(Boolean).length/5*100):0,[state]);
 if(!state)return <FlirtschatLoader context="settings"/>;
 const update=(next:SafetyState)=>{setState(next);saveSafetyState(next)},flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(""),2500)};
 const remaining=state.checkIn?Math.max(0,new Date(state.checkIn.endsAt).getTime()-now):0,remainingText=`${String(Math.floor(remaining/60000)).padStart(2,"0")}:${String(Math.floor(remaining/1000)%60).padStart(2,"0")}`;
 const start=(minutes:number)=>{update({...state,checkIn:{minutes,endsAt:new Date(Date.now()+minutes*60000).toISOString()}});flash(`${minutes}-minute safety check-in started`)};
 const saveContact=()=>state.contact.name.trim()&&state.contact.phone.trim()?(saveSafetyState(state),flash("Trusted contact saved")):flash("Add a name and phone number first");
 return <main className="safety-page"><header className="safety-header"><Link href="/settings" aria-label="Back to settings"><ArrowLeft/></Link><div><h1>Safety Center</h1><p>Tools for safer, confident connections</p></div><i><ShieldCheck/></i></header><div className="safety-shell"><section className="safety-score"><div className="safety-score-ring" style={{"--score":`${score*3.6}deg`} as CSSProperties}><strong>{score}%</strong></div><span><b>Your safety readiness</b><small>{score===100?"Every recommended step is complete.":"Complete the checklist before meeting someone."}</small></span><BadgeCheck/></section>
 <SafetyCard icon={<UserRoundCheck/>} accent="green" title="Before you meet" detail="Interactive dating safety checklist"><div className="safety-checklist">{checks.map(([key,label,detail])=><label key={key}><input type="checkbox" checked={state.checklist[key]} onChange={()=>update({...state,checklist:{...state.checklist,[key]:!state.checklist[key]}})}/><i><Check/></i><span><strong>{label}</strong><small>{detail}</small></span></label>)}</div></SafetyCard>
 <SafetyCard icon={<Clock3/>} accent="violet" title="Safety check-in" detail="Set a timer while you are on a date">{state.checkIn&&remaining>0?<div className="safety-running"><span><small>Check-in countdown</small><strong>{remainingText}</strong></span><button type="button" onClick={()=>update({...state,checkIn:null})}><Square/>I&apos;m safe</button></div>:<div className="safety-timers">{[30,60,120].map(minutes=><button type="button" onClick={()=>start(minutes)} key={minutes}><Play/>{minutes<60?`${minutes} min`:`${minutes/60} hr`}</button>)}</div>}</SafetyCard>
 <SafetyCard icon={<Phone/>} accent="pink" title="Trusted contact" detail="Keep one emergency contact ready"><div className="safety-contact"><input aria-label="Trusted contact name" placeholder="Contact name" value={state.contact.name} onChange={event=>update({...state,contact:{...state.contact,name:event.target.value}})}/><input aria-label="Trusted contact phone" placeholder="Phone number" inputMode="tel" value={state.contact.phone} onChange={event=>update({...state,contact:{...state.contact,phone:event.target.value}})}/><button type="button" onClick={saveContact}>Save contact</button></div></SafetyCard>
 <section className="safety-tools"><h2>Safety tools</h2><Tool href="/settings/privacy" icon={<LockKeyhole/>} accent="green" title="Privacy controls" detail="Manage visibility and contact permissions"/><Tool href="/settings/blocked" icon={<UserRoundX/>} accent="red" title="Blocked users" detail="Review and unblock accounts"/><Tool href="/settings/security" icon={<ShieldCheck/>} accent="blue" title="Account security" detail="Review devices and login protection"/></section>
 <section className="safety-reports"><header><span><h2>Recent reports</h2><p>Reports are private and reviewed by the safety team.</p></span><FileWarning/></header>{state.reports.length?state.reports.slice(0,4).map(report=><article key={report.id}><i><FileWarning/></i><span><strong>{report.reason}</strong><small>{report.profileId.replace("-global","")} · {new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric"}).format(new Date(report.createdAt))}</small></span><b>{report.status}</b></article>):<div><Check/><span><strong>No recent reports</strong><small>Your submitted reports will appear here.</small></span></div>}</section><aside className="safety-emergency"><MapPin/><span><strong>In immediate danger?</strong><small>Contact local emergency services. Flirtschat cannot dispatch emergency help.</small></span></aside></div>{notice&&<div className="safety-toast" role="status"><Check/>{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><X/></button></div>}<AppBottomNav active="settings"/></main>
}
function SafetyCard({icon,accent,title,detail,children}:{icon:ReactNode;accent:string;title:string;detail:string;children:ReactNode}){return <section className="safety-card"><header><i className={accent}>{icon}</i><span><strong>{title}</strong><small>{detail}</small></span></header>{children}</section>}
function Tool({href,icon,accent,title,detail}:{href:string;icon:ReactNode;accent:string;title:string;detail:string}){return <Link href={href}><i className={accent}>{icon}</i><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight/></Link>}
