"use client";
import {BadgeCheck,Check,Clock3,Crown,Heart,LoaderCircle,MessageCircle,RefreshCcw,X} from "lucide-react";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {DesktopSidebar} from "@/components/dashboard/desktop-sidebar";
import {usePresence} from "@/components/presence/presence-provider";
import {ProfileImage} from "@/components/profile-image";
import {FlirtschatLoader} from "@/components/ui/flirtschat-loader";
import {acceptConnection,cancelConnectionRequest,declineConnection,getMyConnections,openConnectionConversation,type ConnectionPerson} from "@/lib/connect-service";
import {createClient} from "@/lib/supabase/client";
import {markMatchViewed,openMatchConversation} from "@/lib/chat/chat-service";
import {useCurrentProfile} from "@/components/profile/current-profile-provider";

type Tab="connected"|"requests"|"legacy";
type LegacyMatch={id:string;profileId:string;name:string;username:string|null;avatarUrl:string|null;verified:boolean;isNew:boolean};
type LegacyRow={match_id:string;profile_id:string;display_name:string|null;username:string|null;photo_key:string|null;verified:boolean|null;is_new:boolean};
const media=(key:string|null)=>key?`/api/media/profile-photo?key=${encodeURIComponent(key)}`:null;

export function MatchesExperience(){
 const router=useRouter(),{user}=useCurrentProfile(),[connections,setConnections]=useState<ConnectionPerson[]>([]),[legacy,setLegacy]=useState<LegacyMatch[]>([]),[tab,setTab]=useState<Tab>("requests"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busyId,setBusyId]=useState<string|null>(null),[actionError,setActionError]=useState("");
 const load=useCallback(async()=>{setError("");try{const supabase=createClient();const[connectionData,{data:legacyData,error:legacyError}]=await Promise.all([getMyConnections(),supabase.rpc("fc_my_matches_with_status")]);if(legacyError)console.error("[connections:legacy] load failed",{code:legacyError.code});setConnections(connectionData);const rows=(legacyData??[])as LegacyRow[];setLegacy(rows.map(row=>({id:row.match_id,profileId:row.profile_id,name:row.display_name||row.username||"Flirtschat member",username:row.username,avatarUrl:media(row.photo_key),verified:Boolean(row.verified),isNew:Boolean(row.is_new)})))}catch{setError("Connections couldn&apos;t load. Try again.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const supabase=createClient(),channel=supabase.channel("current-user-relationships").on("postgres_changes",{event:"*",schema:"public",table:"fc_connections"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"fc_matches"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
 const incoming=useMemo(()=>connections.filter(x=>x.status==="incoming"),[connections]),outgoing=useMemo(()=>connections.filter(x=>x.status==="requested"),[connections]),connected=useMemo(()=>connections.filter(x=>x.status==="connected"),[connections]);
 const update=(id:string,changes:Partial<ConnectionPerson>)=>setConnections(items=>items.map(item=>item.connectionId===id?{...item,...changes}:item));
 const run=async(person:ConnectionPerson,operation:"accept"|"decline"|"cancel")=>{if(busyId)return;setBusyId(person.connectionId);setActionError("");if(operation==="accept")update(person.connectionId,{status:"connected"});else setConnections(items=>items.filter(item=>item.connectionId!==person.connectionId));try{if(operation==="accept")await acceptConnection(person.connectionId);else if(operation==="decline")await declineConnection(person.connectionId);else await cancelConnectionRequest(person.connectionId)}catch{setConnections(items=>items.some(item=>item.connectionId===person.connectionId)?items.map(item=>item.connectionId===person.connectionId?person:item):[...items,person]);setActionError(operation==="cancel"?"Could not cancel this request. Try again.":operation==="accept"?"Could not accept this request.":"Could not decline this request.")}finally{setBusyId(null)}};
 const openChat=async(person:ConnectionPerson)=>{if(busyId)return;setBusyId(person.connectionId);try{const id=await openConnectionConversation(person.connectionId);if(process.env.NODE_ENV==="development")console.debug("[ConnectChatFlow]",{stage:"navigation-start",connectionId:person.connectionId,conversationId:id,authUserPresent:Boolean(user?.id),path:window.location.pathname});router.push(`/chats/${id}`)}catch(error){if(process.env.NODE_ENV==="development")console.error("[ConnectChatFailure]",{stage:"open-chat",connectionId:person.connectionId,authUserPresent:Boolean(user?.id),path:window.location.pathname,errorCode:typeof error==="object"&&error&&"code"in error?String(error.code):null,errorMessage:error instanceof Error?error.message:"Conversation unavailable"});setActionError("Conversation unavailable.");setBusyId(null)}};
 const openLegacyChat=async(person:LegacyMatch)=>{if(busyId)return;setBusyId(person.id);try{const id=await openMatchConversation(person.id);router.push(`/chats/${id}`)}catch{setActionError("Conversation unavailable.");setBusyId(null)}};
 const openLegacyProfile=async(person:LegacyMatch)=>{if(person.isNew){setLegacy(items=>items.map(item=>item.id===person.id?{...item,isNew:false}:item));void markMatchViewed(person.id).catch(()=>undefined)}router.push(`/profile/${person.profileId}`)};
 if(loading)return <FlirtschatLoader context="matches"/>;
 return <main className="matches-page"><DesktopSidebar active="matches"/><div className="matches-shell"><header className="connections-heading"><span>Relationship hub</span><h1>Connections</h1><p>Keep your requests and conversations in one place.</p></header>{actionError&&<div className="connections-error" role="alert">{actionError}<button type="button" onClick={()=>setActionError("")} aria-label="Dismiss error"><X/></button></div>}<div className="connections-tabs" role="tablist" aria-label="Connection sections"><button type="button" role="tab" aria-selected={tab==="requests"} className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}><Clock3/>Requests<b>{incoming.length+outgoing.length}</b></button><button type="button" role="tab" aria-selected={tab==="connected"} className={tab==="connected"?"active":""} onClick={()=>setTab("connected")}><Heart/>Connected<b>{connected.length}</b></button><button type="button" role="tab" aria-selected={tab==="legacy"} className={tab==="legacy"?"active":""} onClick={()=>setTab("legacy")}><Crown/>Matches<b>{legacy.length}</b></button></div>{error?<div className="connections-empty"><RefreshCcw/><p>Connections couldn&apos;t load.</p><button type="button" onClick={()=>void load()}>Retry</button></div>:tab==="legacy"?<div className="connections-list">{legacy.length?legacy.map(person=><LegacyConnection key={person.id} person={person} busy={busyId===person.id} onProfile={()=>void openLegacyProfile(person)} onChat={()=>void openLegacyChat(person)}/>):<Empty text="No legacy matches yet."/>}</div>:<>{tab==="requests"?<div className="connection-request-sections"><RequestSection title="Incoming Requests" people={incoming} busyId={busyId} onAccept={person=>void run(person,"accept")} onDecline={person=>void run(person,"decline")} onCancel={person=>void run(person,"cancel")} onChat={person=>void openChat(person)}/><RequestSection title="Outgoing Requests" people={outgoing} busyId={busyId} onAccept={person=>void run(person,"accept")} onDecline={person=>void run(person,"decline")} onCancel={person=>void run(person,"cancel")} onChat={person=>void openChat(person)}/></div>:<div className="connections-list">{connected.length?connected.map(person=><ConnectionRow key={person.connectionId} person={person} busy={busyId===person.connectionId} onAccept={()=>void run(person,"accept")} onDecline={()=>void run(person,"decline")} onCancel={()=>void run(person,"cancel")} onChat={()=>void openChat(person)}/>):<Empty text="No connected people yet."/>}</div>}</>}</div><AppBottomNav active="matches"/></main>;
}
function Empty({text}:{text:string}){return <div className="connections-empty"><Heart/><p>{text}</p></div>}
function RequestSection({title,people,busyId,onAccept,onDecline,onCancel,onChat}:{title:string;people:ConnectionPerson[];busyId:string|null;onAccept:(person:ConnectionPerson)=>void;onDecline:(person:ConnectionPerson)=>void;onCancel:(person:ConnectionPerson)=>void;onChat:(person:ConnectionPerson)=>void}){return <section className="connection-request-section"><h2>{title}<b>{people.length}</b></h2>{people.length?people.map(person=><ConnectionRow key={person.connectionId} person={person} busy={busyId===person.connectionId} onAccept={()=>onAccept(person)} onDecline={()=>onDecline(person)} onCancel={()=>onCancel(person)} onChat={()=>onChat(person)}/>):<p className="connection-request-empty">No requests here.</p>}</section>}
function ConnectionRow({person,busy,onAccept,onDecline,onCancel,onChat}:{person:ConnectionPerson;busy:boolean;onAccept:()=>void;onDecline:()=>void;onCancel:()=>void;onChat:()=>void}){const presence=usePresence(person.id);return <article className="connection-row"><a href={`/profile/${person.id}`} className="connection-person"><span className="connection-avatar"><ProfileImage src={person.photoUrl} alt={person.name}/><i className={presence.online?"online":""} aria-label={presence.online?"Online":"Offline"}/></span><span><strong>{person.name}{person.age!==null&&<small>, {person.age}</small>}{person.verified&&<BadgeCheck/>}</strong><em>{person.username?`@${person.username}`:"Flirtschat member"}</em><label>{presence.online?"Online now":presence.label}</label></span></a><div className="connection-actions">{person.status==="connected"&&<><b className="connection-status"><Check/>Connected</b><button type="button" className="connection-chat" onClick={onChat} disabled={busy} aria-label={`Chat with ${person.name}`}>{busy?<LoaderCircle className="spin"/>:<MessageCircle/>}</button></>}{person.status==="incoming"&&<><button type="button" className="connection-primary" onClick={onAccept} disabled={busy} aria-label={`Accept connection from ${person.name}`}>{busy?<LoaderCircle className="spin"/>:<><Check/>Accept</>}</button><button type="button" className="connection-secondary" onClick={onDecline} disabled={busy} aria-label={`Decline connection from ${person.name}`}><X/></button></>}{person.status==="requested"&&<><b className="connection-status requested"><Clock3/>Requested</b><button type="button" className="connection-secondary" onClick={onCancel} disabled={busy} aria-label={`Undo request to ${person.name}`}>{busy?<LoaderCircle className="spin"/>:<X/>}</button></>}</div></article>}
function LegacyConnection({person,busy,onProfile,onChat}:{person:LegacyMatch;busy:boolean;onProfile:()=>void;onChat:()=>void}){const presence=usePresence(person.profileId);return <article className="connection-row"><button type="button" className="connection-person" onClick={onProfile}><span className="connection-avatar"><ProfileImage src={person.avatarUrl} alt={person.name}/><i className={presence.online?"online":""}/></span><span><strong>{person.name}{person.verified&&<BadgeCheck/>}</strong><em>{person.username?`@${person.username}`:"Legacy match"}</em><label>{presence.online?"Online now":presence.label}</label></span></button><div className="connection-actions"><b className="connection-status legacy"><Heart/>Match</b><button type="button" className="connection-chat" onClick={onChat} disabled={busy} aria-label={`Chat with ${person.name}`}>{busy?<LoaderCircle className="spin"/>:<MessageCircle/>}</button></div></article>}
