begin;
select pg_advisory_xact_lock(hashtext('flirtschat:202608020002_safety_growth_realtime'));

alter table public.fc_profile_photos add column if not exists moderation_status text not null default 'pending';
alter table public.fc_profile_photos add column if not exists moderator_notes text;
alter table public.fc_profile_photos add column if not exists moderation_metadata jsonb not null default '{}'::jsonb;
alter table public.fc_profile_photos add column if not exists reviewed_at timestamptz;
alter table public.fc_reports add column if not exists photo_id uuid references public.fc_profile_photos(id) on delete set null;
alter table public.fc_reports add column if not exists updated_at timestamptz not null default now();

create table if not exists public.fc_safety_contacts (
  user_id uuid primary key references public.fc_profiles(id) on delete cascade,
  name text not null, phone text not null, updated_at timestamptz not null default now()
);
create table if not exists public.fc_profile_visits (
  id bigint generated by default as identity primary key,
  viewer_id uuid not null references public.fc_profiles(id) on delete cascade,
  viewed_id uuid not null references public.fc_profiles(id) on delete cascade,
  seen boolean not null default false, viewed_at timestamptz not null default now(),
  check(viewer_id<>viewed_id)
);
create table if not exists public.fc_coin_wallets (
  user_id uuid primary key references public.fc_profiles(id) on delete cascade,
  balance integer not null default 0 check(balance>=0), updated_at timestamptz not null default now()
);
create table if not exists public.fc_gifts (
  id text primary key, name text not null, emoji text not null, coin_cost integer not null check(coin_cost>0),
  premium_only boolean not null default false, active boolean not null default true
);
create table if not exists public.fc_coin_transactions (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.fc_profiles(id) on delete cascade,
  amount integer not null check(amount<>0), kind text not null, reference_id uuid,
  description text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.fc_gift_events (
  id uuid primary key default gen_random_uuid(), sender_id uuid not null references public.fc_profiles(id) on delete cascade,
  recipient_id uuid not null references public.fc_profiles(id) on delete cascade, gift_id text not null references public.fc_gifts(id),
  coin_cost integer not null check(coin_cost>0), message text, created_at timestamptz not null default now(), check(sender_id<>recipient_id)
);
create table if not exists public.fc_daily_rewards (
  user_id uuid not null references public.fc_profiles(id) on delete cascade, reward_date date not null default current_date,
  coins integer not null default 25 check(coins>0), claimed_at timestamptz not null default now(), primary key(user_id,reward_date)
);
create table if not exists public.fc_admin_audit_logs (
  id bigint generated by default as identity primary key, actor_id uuid references public.fc_profiles(id) on delete set null,
  action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.fc_gifts(id,name,emoji,coin_cost,premium_only) values
 ('rose','Rose','🌹',10,false),('heart','Heart','💖',20,false),('chocolate','Chocolate','🍫',35,false),
 ('teddy','Teddy','🧸',60,false),('diamond','Diamond','💎',150,true),('crown','Crown','👑',250,true)
on conflict(id) do nothing;

create index if not exists fc_reports_reporter_created_idx on public.fc_reports(reporter_id,created_at desc);
create index if not exists fc_reports_status_created_idx on public.fc_reports(status,created_at desc);
create index if not exists fc_profile_photos_moderation_idx on public.fc_profile_photos(moderation_status,created_at);
create index if not exists fc_profile_visits_viewed_idx on public.fc_profile_visits(viewed_id,viewed_at desc);
create index if not exists fc_profile_visits_viewer_idx on public.fc_profile_visits(viewer_id,viewed_at desc);
create index if not exists fc_coin_transactions_user_idx on public.fc_coin_transactions(user_id,created_at desc);
create index if not exists fc_gift_events_recipient_idx on public.fc_gift_events(recipient_id,created_at desc);
create index if not exists fc_gift_events_sender_idx on public.fc_gift_events(sender_id,created_at desc);
create index if not exists fc_admin_audit_created_idx on public.fc_admin_audit_logs(created_at desc);

alter table public.fc_safety_contacts enable row level security;
alter table public.fc_profile_visits enable row level security;
alter table public.fc_coin_wallets enable row level security;
alter table public.fc_gifts enable row level security;
alter table public.fc_coin_transactions enable row level security;
alter table public.fc_gift_events enable row level security;
alter table public.fc_daily_rewards enable row level security;
alter table public.fc_admin_audit_logs enable row level security;

do $$ begin create policy "users manage own safety contact" on public.fc_safety_contacts for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "users record profile visits" on public.fc_profile_visits for insert to authenticated with check(viewer_id=(select auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "users view their visitors" on public.fc_profile_visits for select to authenticated using(viewed_id=(select auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "users mark visits seen" on public.fc_profile_visits for update to authenticated using(viewed_id=(select auth.uid())) with check(viewed_id=(select auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "users view own wallet" on public.fc_coin_wallets for select to authenticated using(user_id=(select auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "authenticated users view gifts" on public.fc_gifts for select to authenticated using(active); exception when duplicate_object then null; end $$;
do $$ begin create policy "users view own transactions" on public.fc_coin_transactions for select to authenticated using(user_id=(select auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "users view sent or received gifts" on public.fc_gift_events for select to authenticated using((select auth.uid()) in (sender_id,recipient_id)); exception when duplicate_object then null; end $$;
do $$ begin create policy "users view own rewards" on public.fc_daily_rewards for select to authenticated using(user_id=(select auth.uid())); exception when duplicate_object then null; end $$;

create or replace function public.fc_claim_daily_reward() returns integer language plpgsql security definer set search_path='' as $$
declare uid uuid := auth.uid(); reward integer := 25; new_balance integer;
begin
  if uid is null then raise exception 'authentication required'; end if;
  insert into public.fc_daily_rewards(user_id,coins) values(uid,reward) on conflict do nothing;
  if not found then raise exception 'daily reward already claimed'; end if;
  insert into public.fc_coin_wallets(user_id,balance) values(uid,reward)
    on conflict(user_id) do update set balance=public.fc_coin_wallets.balance+reward,updated_at=now() returning balance into new_balance;
  insert into public.fc_coin_transactions(user_id,amount,kind,description) values(uid,reward,'daily_reward','Daily reward');
  return new_balance;
end $$;
create or replace function public.fc_send_gift(recipient uuid,gift text,gift_message text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare uid uuid := auth.uid(); price integer; premium_required boolean; is_premium boolean; event_id uuid;
begin
  if uid is null or uid=recipient then raise exception 'invalid recipient'; end if;
  select coin_cost,premium_only into price,premium_required from public.fc_gifts where id=gift and active;
  if price is null then raise exception 'gift unavailable'; end if;
  select premium into is_premium from public.fc_profiles where id=uid;
  if premium_required and not coalesce(is_premium,false) then raise exception 'premium required'; end if;
  update public.fc_coin_wallets set balance=balance-price,updated_at=now() where user_id=uid and balance>=price;
  if not found then raise exception 'insufficient coins'; end if;
  insert into public.fc_gift_events(sender_id,recipient_id,gift_id,coin_cost,message) values(uid,recipient,gift,price,left(gift_message,240)) returning id into event_id;
  insert into public.fc_coin_transactions(user_id,amount,kind,reference_id,description) values(uid,-price,'gift_sent',event_id,'Sent '||gift);
  return event_id;
end $$;
grant execute on function public.fc_claim_daily_reward() to authenticated;
grant execute on function public.fc_send_gift(uuid,text,text) to authenticated;

do $$ declare table_name text; begin
  foreach table_name in array array['fc_reports','fc_profile_photos','fc_profile_visits','fc_coin_wallets','fc_coin_transactions','fc_gift_events'] loop
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=table_name) then
      execute format('alter publication supabase_realtime add table public.%I',table_name);
    end if;
  end loop;
end $$;
commit;
