"use client";

import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {deleteNotificationRemote,loadNotificationById,loadNotifications,loadUnreadNotificationCount,markAllNotificationsRead,markNotificationRead} from "@/lib/notifications/notification-service";
import type {FlirtschatNotification} from "@/lib/notifications/notification-types";
import {clearUserCache,getUserCache,setUserCache} from "@/lib/app-cache";

type NotificationContextValue={items:FlirtschatNotification[];unreadCount:number;unreadNotificationCount:number;refresh:()=>Promise<void>;markRead:(id:string)=>Promise<void>;markAllRead:()=>Promise<void>;remove:(id:string)=>Promise<void>};
const NotificationContext=createContext<NotificationContextValue|null>(null);

export function NotificationProvider({children}:{children:React.ReactNode}){
  const router=useRouter(),[items,setItems]=useState<FlirtschatNotification[]>([]),[unreadNotificationCount,setUnreadNotificationCount]=useState(0),[toast,setToast]=useState<FlirtschatNotification|null>(null),activeChannel=useRef<ReturnType<ReturnType<typeof createClient>["channel"]>|null>(null),activeUserId=useRef<string|null>(null);
  const refresh=useCallback(async()=>{const userId=activeUserId.current;const cached=userId?getUserCache<FlirtschatNotification[]>(userId,"notifications",30000):undefined;if(cached)setItems(cached);try{const next=await loadNotifications();if(userId)setUserCache(userId,"notifications",next);setItems(next)}catch{if(!cached)setItems([])}},[]);
  const refreshCount=useCallback(async()=>{try{setUnreadNotificationCount(await loadUnreadNotificationCount())}catch{setUnreadNotificationCount(0)}},[]);
  useEffect(()=>{
    const supabase=createClient();let disposed=false;let connectedUserId:string|null=null;let connectingUserId:string|null=null;let generation=0;let lifecycle=Promise.resolve();let countTimer:number|null=null;const processedEvents=new Set<string>();let subscription:ReturnType<typeof supabase.auth.onAuthStateChange>["data"]["subscription"]|null=null;
    const enqueue=(task:()=>Promise<void>)=>{const next=lifecycle.then(task,task);lifecycle=next.catch(()=>undefined);return next};
    const cleanup=()=>{generation+=1;connectedUserId=null;connectingUserId=null;const oldChannel=activeChannel.current;activeChannel.current=null;if(countTimer!==null){window.clearTimeout(countTimer);countTimer=null}return enqueue(async()=>{if(oldChannel)await supabase.removeChannel(oldChannel)})};
    const reconcileCount=()=>{if(countTimer!==null)window.clearTimeout(countTimer);countTimer=window.setTimeout(()=>{countTimer=null;void refreshCount()},250)};
    const connect=(userId:string)=>{if(disposed||connectedUserId===userId||connectingUserId===userId)return;activeUserId.current=userId;const myGeneration=++generation;connectingUserId=userId;void enqueue(async()=>{if(disposed||myGeneration!==generation)return;const oldChannel=activeChannel.current;activeChannel.current=null;connectedUserId=null;if(oldChannel)await supabase.removeChannel(oldChannel);if(disposed||myGeneration!==generation)return;await Promise.all([refresh(),refreshCount()]);if(disposed||myGeneration!==generation)return;processedEvents.clear();const nextChannel=supabase.channel(`user-notifications-${userId}-${myGeneration}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"fc_notifications",filter:`user_id=eq.${userId}`},payload=>{const row=payload.new as {id?:string;read_at?:string|null},id=String(row.id??"");if(!id||processedEvents.has(`insert:${id}`))return;processedEvents.add(`insert:${id}`);if(!row.read_at)setUnreadNotificationCount(current=>current+1);void loadNotificationById(id).then(notice=>{if(!notice||disposed)return;setUserCache(userId,"notifications",[notice,...(getUserCache<FlirtschatNotification[]>(userId,"notifications")??[]).filter(item=>item.id!==id)]);setItems(current=>[notice,...current.filter(item=>item.id!==id)]);setToast(notice);window.setTimeout(()=>setToast(current=>current?.id===id?null:current),4500)}).catch(()=>undefined);reconcileCount()}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"fc_notifications",filter:`user_id=eq.${userId}`},payload=>{const oldRow=payload.old as {id?:string;read_at?:string|null},newRow=payload.new as {id?:string;read_at?:string|null},id=String(newRow.id??oldRow.id??""),key=`update:${id}:${newRow.read_at??"unread"}`;if(!id||processedEvents.has(key))return;processedEvents.add(key);if(!oldRow.read_at&&newRow.read_at)setUnreadNotificationCount(current=>Math.max(0,current-1));else if(oldRow.read_at&&!newRow.read_at)setUnreadNotificationCount(current=>current+1);setItems(current=>current.map(item=>item.id===id?{...item,read:Boolean(newRow.read_at)}:item));reconcileCount()}).on("postgres_changes",{event:"DELETE",schema:"public",table:"fc_notifications",filter:`user_id=eq.${userId}`},payload=>{const row=payload.old as {id?:string;read_at?:string|null},id=String(row.id??"");if(!id||processedEvents.has(`delete:${id}`))return;processedEvents.add(`delete:${id}`);if(!row.read_at)setUnreadNotificationCount(current=>Math.max(0,current-1));setItems(current=>current.filter(item=>item.id!==id));reconcileCount()});if(disposed||myGeneration!==generation){await supabase.removeChannel(nextChannel);return}activeChannel.current=nextChannel;connectedUserId=userId;connectingUserId=null;try{nextChannel.subscribe()}catch{if(activeChannel.current===nextChannel)activeChannel.current=null;connectedUserId=null;await supabase.removeChannel(nextChannel)}})};
    void supabase.auth.getUser().then(({data})=>{if(!disposed&&data.user)connect(data.user.id)}).catch(()=>undefined);subscription=supabase.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){clearUserCache(activeUserId.current??undefined);activeUserId.current=null;void cleanup();processedEvents.clear();setItems([]);setUnreadNotificationCount(0);return}if(session?.user)connect(session.user.id)}).data.subscription;return()=>{disposed=true;void cleanup();subscription?.unsubscribe()}
  },[refresh,refreshCount]);
  const markRead=useCallback(async(id:string)=>{const item=items.find(entry=>entry.id===id);setItems(current=>current.map(entry=>entry.id===id?{...entry,read:true}:entry));if(item&&!item.read)setUnreadNotificationCount(current=>Math.max(0,current-1));try{await markNotificationRead(id)}catch{await refresh();await refreshCount()}},[items,refresh,refreshCount]);
  const markAllRead=useCallback(async()=>{setItems(current=>current.map(item=>({...item,read:true})));setUnreadNotificationCount(0);try{await markAllNotificationsRead()}catch{await refresh();await refreshCount()}},[refresh,refreshCount]);
  const remove=useCallback(async(id:string)=>{const item=items.find(entry=>entry.id===id);setItems(current=>current.filter(entry=>entry.id!==id));if(item&&!item.read)setUnreadNotificationCount(current=>Math.max(0,current-1));try{await deleteNotificationRemote(id)}catch{await refresh();await refreshCount()}},[items,refresh,refreshCount]);
  const value=useMemo(()=>({items,unreadCount:unreadNotificationCount,unreadNotificationCount,refresh,markRead,markAllRead,remove}),[items,markAllRead,markRead,refresh,remove,unreadNotificationCount]);
  return <NotificationContext.Provider value={value}>{children}{toast&&<button type="button" className="fc-notification-toast" onClick={()=>{setToast(null);if(!toast.read)void markRead(toast.id);router.push(toast.href)}}><span><strong>{toast.title}</strong><small>{toast.description||"Open notifications"}</small></span></button>}</NotificationContext.Provider>;
}

export function useNotifications(){const value=useContext(NotificationContext);if(!value)throw new Error("useNotifications must be used within NotificationProvider");return value}
