"use client";
/* eslint-disable @next/next/no-img-element -- private media is served by an authenticated route. */

import {AlertCircle,Globe2,Image as ImageIcon,LoaderCircle,MoreHorizontal,Send,Trash2,X} from "lucide-react";
import {useCallback,useEffect,useRef,useState} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {DesktopSidebar} from "@/components/dashboard/desktop-sidebar";
import {ProfileImage} from "@/components/profile-image";
import {useCurrentProfile} from "@/components/profile/current-profile-provider";
import {FlirtschatLoader} from "@/components/ui/flirtschat-loader";
import {FlirtschatSkeleton} from "@/components/ui/flirtschat-skeleton";
import {blockUser,reportUser} from "@/lib/community-service";
import {createClient} from "@/lib/supabase/client";
import {deleteGlobalPost,GLOBAL_IMAGE_MAX_BYTES,GLOBAL_IMAGE_TYPES,loadGlobalPost,loadGlobalPosts,postImageUrl,type GlobalCursor,type GlobalPost} from "@/lib/global-feed-service";
import {useRouter} from "next/navigation";

const profilePhoto=(key:string|null)=>key?`/api/media/profile-photo?key=${encodeURIComponent(key)}`:null;
const relativeTime=(value:string)=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return "Just now";const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes}m`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h`;const days=Math.floor(hours/24);return days<7?`${days}d`:new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"})};

export default function GlobalPage(){
  const router=useRouter(),{profile,user,loading:profileLoading,authStatus}=useCurrentProfile();
  const[posts,setPosts]=useState<GlobalPost[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[cursor,setCursor]=useState<GlobalCursor|null>(null),[hasMore,setHasMore]=useState(true),[composerOpen,setComposerOpen]=useState(false),[menuId,setMenuId]=useState<string|null>(null),[notice,setNotice]=useState("");
  const load=useCallback(async(nextCursor?:GlobalCursor)=>{try{setError(false);const rows=await loadGlobalPosts(nextCursor);setPosts(current=>nextCursor?[...current,...rows]:rows);setCursor(rows.length?{createdAt:rows[rows.length-1].createdAt,id:rows[rows.length-1].id}:nextCursor??null);setHasMore(rows.length===30)}catch{setError(true)}finally{setLoading(false)}},[]);
  useEffect(()=>{if(authStatus==="unauthenticated")router.replace("/login")},[authStatus,router]);
  useEffect(()=>{if(authStatus!=="authenticated")return;void load()},[authStatus,load]);
  useEffect(()=>{
    if(authStatus!=="authenticated")return;
    const supabase=createClient(),channel=supabase.channel("global-feed-posts")
      .on("postgres_changes",{event:"INSERT",schema:"public",table:"fc_posts"},payload=>{const id=String((payload.new as {id?:string}).id??"");if(!id)return;void loadGlobalPost(id).then(post=>{if(post)setPosts(current=>current.some(item=>item.id===post.id)?current:[post,...current])}).catch(()=>undefined)})
      .on("postgres_changes",{event:"DELETE",schema:"public",table:"fc_posts"},payload=>{const id=String((payload.old as {id?:string}).id??"");if(id)setPosts(current=>current.filter(post=>post.id!==id))})
      .subscribe();
    return()=>{void supabase.removeChannel(channel)};
  },[authStatus]);
  const removePost=async(post:GlobalPost)=>{setMenuId(null);setPosts(current=>current.filter(item=>item.id!==post.id));try{await deleteGlobalPost(post.id)}catch{setPosts(current=>[post,...current].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()));setNotice("Post couldn’t be deleted. Try again.")}};
  const moderate=async(post:GlobalPost,action:"block"|"report")=>{setMenuId(null);try{if(action==="block"){await blockUser(post.userId);setPosts(current=>current.filter(item=>item.userId!==post.userId));setNotice("Member blocked.")}else{await reportUser(post.userId,"Other","Reported from Global.");setNotice("Report submitted.")}}catch{setNotice(action==="block"?"Couldn’t block this member.":"Report couldn’t be submitted.")}};
  if(profileLoading||authStatus==="loading")return <FlirtschatLoader message="Getting things ready..." variant="page"/>;
  if(!user||!profile)return null;
  return <main className="fc-global-feed-page"><DesktopSidebar mobileOpen={false} onClose={()=>{}} active="global"/><div className="fc-global-feed-shell"><header className="fc-global-feed-header"><div><Globe2/><span><strong>GLOBAL</strong><small>See what&apos;s happening around Flirtschat</small></span></div></header><PostComposer profile={profile} open={composerOpen} onOpen={()=>setComposerOpen(true)} onClose={()=>setComposerOpen(false)} onCreated={post=>setPosts(current=>current.some(item=>item.id===post.id)?current:[post,...current])}/>{loading?<FlirtschatSkeleton variant="matches"/>:error?<section className="fc-global-feed-state"><AlertCircle/><strong>Posts couldn&apos;t load.</strong><button type="button" onClick={()=>void load()}>Retry</button></section>:<section className="fc-global-post-list" aria-label="Global posts">{posts.length?posts.map(post=><PostCard key={post.id} post={post} own={post.userId===user.id} menuOpen={menuId===post.id} onMenu={()=>setMenuId(menuId===post.id?null:post.id)} onDelete={()=>void removePost(post)} onModerate={action=>void moderate(post,action)}/>):<div className="fc-global-feed-state"><Globe2/><strong>No posts yet</strong><span>Be the first to share something.</span></div>}{hasMore&&posts.length>0&&<button className="fc-global-load-more" type="button" onClick={()=>cursor&&void load(cursor)} disabled={!cursor}>Load more</button>}</section>}</div><AppBottomNav active="global"/>{notice&&<button className="fc-global-notice" type="button" onClick={()=>setNotice("")}>{notice}<X/></button>}</main>;
}

function PostComposer({profile,open,onOpen,onClose,onCreated}:{profile:{id:string;displayName:string;primaryPhotoUrl:string|null};open:boolean;onOpen:()=>void;onClose:()=>void;onCreated:(post:GlobalPost)=>void}){
  const[body,setBody]=useState(""),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const choose=(next:File|null)=>{if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):"");setError("");if(inputRef.current)inputRef.current.value=""};
  const submit=async()=>{if(busy||(!body.trim()&&!file))return;setBusy(true);setError("");try{let imageKey:string|null=null;if(file){const response=await fetch("/api/uploads/global-post-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contentType:file.type,size:file.size})});const payload=await response.json().catch(()=>null) as {uploadUrl?:string;objectKey?:string;error?:{message?:string}}|null;if(!response.ok||!payload?.uploadUrl||!payload.objectKey)throw new Error(payload?.error?.message||"Image upload unavailable");const upload=await fetch(payload.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!upload.ok)throw new Error("Image upload failed");imageKey=payload.objectKey}const{data,error:insertError}=await createClient().from("fc_posts").insert({user_id:profile.id,body:body.trim()||null,image_key:imageKey}).select("id").single();if(insertError||!data)throw insertError??new Error("Post could not be created");const created=await loadGlobalPost(data.id);if(!created)throw new Error("Post could not be loaded");onCreated(created);setBody("");choose(null);onClose()}catch(reason){setError(reason instanceof Error?reason.message:"Post could not be created. Try again.")}finally{setBusy(false)}};
  return <><button className="fc-global-composer" type="button" onClick={onOpen}><ProfileImage src={profile.primaryPhotoUrl} alt={profile.displayName||"Your profile"}/><span>What&apos;s on your mind?</span><ImageIcon/></button>{open&&<div className="fc-global-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="fc-global-post-modal" role="dialog" aria-modal="true" aria-labelledby="fc-create-post-title"><header><strong id="fc-create-post-title">Create post</strong><button type="button" onClick={onClose} aria-label="Close create post"><X/></button></header><div className="fc-global-author"><ProfileImage src={profile.primaryPhotoUrl} alt={profile.displayName||"Your profile"}/><strong>{profile.displayName||"Your profile"}</strong></div><textarea autoFocus value={body} onChange={event=>setBody(event.target.value.slice(0,2000))} placeholder="What&apos;s on your mind?" aria-label="Post text"/><input ref={inputRef} className="fc-global-file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const next=event.target.files?.[0]??null;if(next&&!GLOBAL_IMAGE_TYPES.includes(next.type as typeof GLOBAL_IMAGE_TYPES[number])){setError("Use a JPG, PNG or WEBP image.");return}if(next&&next.size>GLOBAL_IMAGE_MAX_BYTES){setError("Images must be under 10 MB.");return}choose(next)}}/>{preview&&<div className="fc-global-preview"><img src={preview} alt="Selected post preview"/><button type="button" onClick={()=>choose(null)} aria-label="Remove selected image"><X/></button></div>}<footer>{error&&<p role="alert">{error}</p>}<button type="button" className="fc-global-add-image" onClick={()=>inputRef.current?.click()}><ImageIcon/>Add image</button><button type="button" className="fc-global-post-button" disabled={busy||(!body.trim()&&!file)} onClick={()=>void submit()}>{busy?<><LoaderCircle className="fc-spin"/>Posting…</>:<><Send/>Post</>}</button></footer></section></div>}</>;
}

function PostCard({post,own,menuOpen,onMenu,onDelete,onModerate}:{post:GlobalPost;own:boolean;menuOpen:boolean;onMenu:()=>void;onDelete:()=>void;onModerate:(action:"block"|"report")=>void}){return <article className="fc-global-post-card"><header><a href={`/profile/${post.userId}`} className="fc-global-post-author"><ProfileImage src={profilePhoto(post.photoKey)} alt={post.name}/><span><strong>{post.name}{post.verified&&<b aria-label="Verified">✓</b>}</strong><small>{post.username?`@${post.username}`:"Flirtschat member"} · {relativeTime(post.createdAt)}</small></span></a><div className="fc-global-post-menu"><button type="button" onClick={onMenu} aria-label="Post actions" aria-expanded={menuOpen}><MoreHorizontal/></button>{menuOpen&&<div role="menu">{own?<button type="button" role="menuitem" onClick={onDelete}><Trash2/>Delete post</button>:<><button type="button" role="menuitem" onClick={()=>onModerate("report")}>Report post</button><button type="button" role="menuitem" onClick={()=>onModerate("block")}>Block member</button></>}</div>}</div></header>{post.body&&<p>{post.body}</p>}{post.imageKey&&<img className="fc-global-post-image" src={postImageUrl(post.imageKey)} alt={post.body||"Shared post image"} loading="lazy" draggable={false} onContextMenu={event=>event.preventDefault()}/>}</article>}
