"use client";
/* eslint-disable @next/next/no-img-element -- private media is served by an authenticated route. */

import {AlertCircle,Bookmark,Globe2,Heart,Image as ImageIcon,LoaderCircle,MessageCircle,MoreHorizontal,Send,Share2,Trash2,X} from "lucide-react";
import {useCallback,useEffect,useRef,useState} from "react";
import {AppBottomNav} from "@/components/app-bottom-nav";
import {DesktopSidebar} from "@/components/dashboard/desktop-sidebar";
import {ProfileImage} from "@/components/profile-image";
import {useCurrentProfile} from "@/components/profile/current-profile-provider";
import {FlirtschatLoader} from "@/components/ui/flirtschat-loader";
import {FlirtschatSkeleton} from "@/components/ui/flirtschat-skeleton";
import {blockUser,reportUser} from "@/lib/community-service";
import {createClient} from "@/lib/supabase/client";
import {createPostComment,deleteGlobalPost,deletePostComment,GLOBAL_IMAGE_MAX_BYTES,GLOBAL_IMAGE_TYPES,loadGlobalPost,loadGlobalPosts,loadPostComment,loadPostComments,loadPostInteractionSummary,postImageUrl,recordPostShare,togglePostHeart,togglePostSave,type GlobalComment,type GlobalCursor,type GlobalPost} from "@/lib/global-feed-service";
import {useRouter} from "next/navigation";

const profilePhoto=(key:string|null)=>key?`/api/media/profile-photo?key=${encodeURIComponent(key)}`:null;
const relativeTime=(value:string)=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return "Just now";const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes}m`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h`;const days=Math.floor(hours/24);return days<7?`${days}d`:new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"})};

export default function GlobalPage(){
  const router=useRouter(),{profile,user,loading:profileLoading,authStatus}=useCurrentProfile();
  const[posts,setPosts]=useState<GlobalPost[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[cursor,setCursor]=useState<GlobalCursor|null>(null),[hasMore,setHasMore]=useState(true),[composerOpen,setComposerOpen]=useState(false),[menuId,setMenuId]=useState<string|null>(null),[openComments,setOpenComments]=useState<Record<string,boolean>>({}),[comments,setComments]=useState<Record<string,GlobalComment[]>>({}),[commentsMore,setCommentsMore]=useState<Record<string,boolean>>({}),[commentLoading,setCommentLoading]=useState<Record<string,boolean>>({}),[interactionBusy,setInteractionBusy]=useState<Record<string,boolean>>({}),[notice,setNotice]=useState("");
  const load=useCallback(async(nextCursor?:GlobalCursor)=>{try{setError(false);const rows=await loadGlobalPosts(nextCursor);setPosts(current=>nextCursor?[...current,...rows]:rows);setCursor(rows.length?{createdAt:rows[rows.length-1].createdAt,id:rows[rows.length-1].id}:nextCursor??null);setHasMore(rows.length===30)}catch{setError(true)}finally{setLoading(false)}},[]);
  useEffect(()=>{if(authStatus==="unauthenticated")router.replace("/login")},[authStatus,router]);
  useEffect(()=>{if(authStatus!=="authenticated")return;void load()},[authStatus,load]);
  const patchPost=(id:string,change:Partial<GlobalPost>)=>setPosts(current=>current.map(post=>post.id===id?{...post,...change}:post));
  const reconcileInteractions=useCallback(async(id:string)=>{try{const summary=await loadPostInteractionSummary([id]);if(summary[id])setPosts(current=>current.map(post=>post.id===id?{...post,...summary[id]}:post))}catch{/* keep the optimistic state when reconciliation is unavailable */}},[]);
  const setBusy=(id:string,value:boolean)=>setInteractionBusy(current=>({...current,[id]:value}));
  const heart=async(post:GlobalPost)=>{if(interactionBusy[post.id])return;const next=!post.heartedByMe;setBusy(post.id,true);patchPost(post.id,{heartedByMe:next,heartCount:Math.max(0,post.heartCount+(next?1:-1))});try{const result=await togglePostHeart(post.id);patchPost(post.id,{heartedByMe:result.hearted,heartCount:result.heartCount})}catch{patchPost(post.id,{heartedByMe:post.heartedByMe,heartCount:post.heartCount});setNotice("Couldn’t update your heart. Try again.")}finally{setBusy(post.id,false)}};
  const save=async(post:GlobalPost)=>{if(interactionBusy[post.id])return;const next=!post.savedByMe;setBusy(post.id,true);patchPost(post.id,{savedByMe:next});try{patchPost(post.id,{savedByMe:await togglePostSave(post.id)})}catch{patchPost(post.id,{savedByMe:post.savedByMe});setNotice("Couldn’t update your saved posts. Try again.")}finally{setBusy(post.id,false)}};
  const share=async(post:GlobalPost)=>{if(typeof window==="undefined")return;const url=`${window.location.origin}/global/post/${post.id}`,nav=navigator as Navigator&{share?:({title,text,url}:{title:string;text:string;url:string})=>Promise<void>;clipboard?:Clipboard};try{if(typeof nav.share==="function")await nav.share({title:"FLIRTSCHAT post",text:post.body?.slice(0,120)||"See this post on FLIRTSCHAT",url});else{if(!nav.clipboard)throw new Error("Clipboard unavailable");await nav.clipboard.writeText(url);setNotice("Link copied")}const count=await recordPostShare(post.id);patchPost(post.id,{shareCount:count})}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;setNotice("Couldn’t share this post. Try again.")}};
  const toggleComments=async(id:string)=>{const next=!openComments[id];setOpenComments(current=>({...current,[id]:next}));if(next&&!comments[id]){setCommentLoading(current=>({...current,[id]:true}));try{const result=await loadPostComments(id);setComments(current=>({...current,[id]:result.comments}));setCommentsMore(current=>({...current,[id]:result.hasMore}))}catch{setNotice("Comments couldn’t load. Try again.")}finally{setCommentLoading(current=>({...current,[id]:false}))}}};
  const loadMore=async(id:string)=>{const rows=comments[id]??[],last=rows[rows.length-1];if(!last||commentLoading[id])return;setCommentLoading(current=>({...current,[id]:true}));try{const result=await loadPostComments(id,10,{createdAt:last.createdAt,id:last.id});setComments(current=>({...current,[id]:[...rows,...result.comments]}));setCommentsMore(current=>({...current,[id]:result.hasMore}))}catch{setNotice("More comments couldn’t load. Try again.")}finally{setCommentLoading(current=>({...current,[id]:false}))}};
  const commentCreated=(comment:GlobalComment)=>{setComments(current=>({...current,[comment.postId]:[...(current[comment.postId]??[]),comment]}));patchPost(comment.postId,{commentCount:(posts.find(post=>post.id===comment.postId)?.commentCount??0)+1})};
  const commentDeleted=(comment:GlobalComment)=>{setComments(current=>({...current,[comment.postId]:(current[comment.postId]??[]).filter(item=>item.id!==comment.id)}));patchPost(comment.postId,{commentCount:Math.max(0,(posts.find(post=>post.id===comment.postId)?.commentCount??1)-1)})};
  useEffect(()=>{
    if(authStatus!=="authenticated")return;
    const supabase=createClient(),channel=supabase.channel("global-feed-interactions")
      .on("postgres_changes",{event:"INSERT",schema:"public",table:"fc_posts"},payload=>{const id=String((payload.new as {id?:string}).id??"");if(!id)return;void loadGlobalPost(id).then(post=>{if(post)setPosts(current=>current.some(item=>item.id===post.id)?current:[post,...current])}).catch(()=>undefined)})
      .on("postgres_changes",{event:"DELETE",schema:"public",table:"fc_posts"},payload=>{const id=String((payload.old as {id?:string}).id??"");if(id)setPosts(current=>current.filter(post=>post.id!==id))})
      .on("postgres_changes",{event:"*",schema:"public",table:"fc_post_likes"},payload=>{const id=String(((payload.new as {post_id?:string}).post_id??(payload.old as {post_id?:string}).post_id)??"");if(id)void reconcileInteractions(id)})
      .on("postgres_changes",{event:"*",schema:"public",table:"fc_post_shares"},payload=>{const id=String(((payload.new as {post_id?:string}).post_id??(payload.old as {post_id?:string}).post_id)??"");if(id)void reconcileInteractions(id)})
      .on("postgres_changes",{event:"*",schema:"public",table:"fc_post_comments"},payload=>{const id=String(((payload.new as {post_id?:string}).post_id??(payload.old as {post_id?:string}).post_id)??"");const commentId=String((payload.new as {id?:string}).id??"");if(id){void reconcileInteractions(id);if(commentId&&payload.eventType==="INSERT")void loadPostComment(commentId).then(comment=>{if(comment)setComments(current=>({...current,[id]:current[id]?(current[id].some(item=>item.id===comment.id)?current[id]:[...current[id],comment]):current[id]}))}).catch(()=>undefined);if(payload.eventType==="DELETE")setComments(current=>({...current,[id]:(current[id]??[]).filter(item=>item.id!==commentId)}))}})
      .subscribe();
    return()=>{void supabase.removeChannel(channel)};
  },[authStatus,reconcileInteractions]);
  const removePost=async(post:GlobalPost)=>{setMenuId(null);setPosts(current=>current.filter(item=>item.id!==post.id));try{await deleteGlobalPost(post.id)}catch{setPosts(current=>[post,...current].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()));setNotice("Post couldn’t be deleted. Try again.")}};
  const moderate=async(post:GlobalPost,action:"block"|"report")=>{setMenuId(null);try{if(action==="block"){await blockUser(post.userId);setPosts(current=>current.filter(item=>item.userId!==post.userId));setNotice("Member blocked.")}else{await reportUser(post.userId,"Other","Reported from Global.");setNotice("Report submitted.")}}catch{setNotice(action==="block"?"Couldn’t block this member.":"Report couldn’t be submitted.")}};
  if(profileLoading||authStatus==="loading")return <FlirtschatLoader message="Getting things ready..." variant="page"/>;
  if(!user||!profile)return null;
  return <main className="fc-global-feed-page"><DesktopSidebar mobileOpen={false} onClose={()=>{}} active="global"/><div className="fc-global-feed-shell"><header className="fc-global-feed-header"><div><Globe2/><span><strong>GLOBAL</strong><small>See what&apos;s happening around Flirtschat</small></span></div></header><PostComposer profile={profile} open={composerOpen} onOpen={()=>setComposerOpen(true)} onClose={()=>setComposerOpen(false)} onCreated={post=>setPosts(current=>current.some(item=>item.id===post.id)?current:[post,...current])}/>{loading?<FlirtschatSkeleton variant="matches"/>:error?<section className="fc-global-feed-state"><AlertCircle/><strong>Posts couldn&apos;t load.</strong><button type="button" onClick={()=>void load()}>Retry</button></section>:<section className="fc-global-post-list" aria-label="Global posts">{posts.length?posts.map(post=><PostCard key={post.id} post={post} own={post.userId===user.id} menuOpen={menuId===post.id} onMenu={()=>setMenuId(menuId===post.id?null:post.id)} onDelete={()=>void removePost(post)} onModerate={action=>void moderate(post,action)} interactionBusy={Boolean(interactionBusy[post.id])} onHeart={()=>void heart(post)} onSave={()=>void save(post)} onShare={()=>void share(post)} commentsOpen={Boolean(openComments[post.id])} comments={comments[post.id]??[]} commentsMore={Boolean(commentsMore[post.id])} commentsLoading={Boolean(commentLoading[post.id])} onComments={()=>void toggleComments(post.id)} onLoadMoreComments={()=>void loadMore(post.id)} onCommentCreated={commentCreated} onCommentDeleted={commentDeleted}/>):<div className="fc-global-feed-state"><Globe2/><strong>No posts yet</strong><span>Be the first to share something.</span></div>}{hasMore&&posts.length>0&&<button className="fc-global-load-more" type="button" onClick={()=>cursor&&void load(cursor)} disabled={!cursor}>Load more</button>}</section>}</div><AppBottomNav active="global"/>{notice&&<button className="fc-global-notice" type="button" onClick={()=>setNotice("")}>{notice}<X/></button>}</main>;
}

function PostComposer({profile,open,onOpen,onClose,onCreated}:{profile:{id:string;displayName:string;primaryPhotoUrl:string|null};open:boolean;onOpen:()=>void;onClose:()=>void;onCreated:(post:GlobalPost)=>void}){
  const[body,setBody]=useState(""),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const choose=(next:File|null)=>{if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):"");setError("");if(inputRef.current)inputRef.current.value=""};
  const submit=async()=>{if(busy||(!body.trim()&&!file))return;setBusy(true);setError("");try{let imageKey:string|null=null;if(file){const response=await fetch("/api/uploads/global-post-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contentType:file.type,size:file.size})});const payload=await response.json().catch(()=>null) as {uploadUrl?:string;objectKey?:string;error?:{message?:string}}|null;if(!response.ok||!payload?.uploadUrl||!payload.objectKey)throw new Error(payload?.error?.message||"Image upload unavailable");const upload=await fetch(payload.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!upload.ok)throw new Error("Image upload failed");imageKey=payload.objectKey}const{data,error:insertError}=await createClient().from("fc_posts").insert({user_id:profile.id,body:body.trim()||null,image_key:imageKey}).select("id").single();if(insertError||!data)throw insertError??new Error("Post could not be created");const created=await loadGlobalPost(data.id);if(!created)throw new Error("Post could not be loaded");onCreated(created);setBody("");choose(null);onClose()}catch(reason){setError(reason instanceof Error?reason.message:"Post could not be created. Try again.")}finally{setBusy(false)}};
  return <><div className="fc-global-composer" role="group" aria-label="Create a post"><button className="fc-global-composer-avatar" type="button" onClick={onOpen} aria-label="Create a post"><ProfileImage src={profile.primaryPhotoUrl} alt={profile.displayName||"Your profile"}/></button><button className="fc-global-composer-pill" type="button" onClick={onOpen} aria-label="Create a post"><span>What&apos;s on your mind?</span></button><button className="fc-global-composer-image" type="button" onClick={onOpen} aria-label="Add image to post"><ImageIcon/></button></div>{open&&<div className="fc-global-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="fc-global-post-modal" role="dialog" aria-modal="true" aria-labelledby="fc-create-post-title"><header><strong id="fc-create-post-title">Create post</strong><button type="button" onClick={onClose} aria-label="Close create post"><X/></button></header><div className="fc-global-author"><ProfileImage src={profile.primaryPhotoUrl} alt={profile.displayName||"Your profile"}/><strong>{profile.displayName||"Your profile"}</strong></div><textarea autoFocus value={body} onChange={event=>setBody(event.target.value.slice(0,2000))} placeholder="What&apos;s on your mind?" aria-label="Post text"/><input ref={inputRef} className="fc-global-file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const next=event.target.files?.[0]??null;if(next&&!GLOBAL_IMAGE_TYPES.includes(next.type as typeof GLOBAL_IMAGE_TYPES[number])){setError("Use a JPG, PNG or WEBP image.");return}if(next&&next.size>GLOBAL_IMAGE_MAX_BYTES){setError("Images must be under 10 MB.");return}choose(next)}}/>{preview&&<div className="fc-global-preview"><img src={preview} alt="Selected post preview"/><button type="button" onClick={()=>choose(null)} aria-label="Remove selected image"><X/></button></div>}<footer>{error&&<p role="alert">{error}</p>}<button type="button" className="fc-global-add-image" onClick={()=>inputRef.current?.click()}><ImageIcon/>Add image</button><button type="button" className="fc-global-post-button" disabled={busy||(!body.trim()&&!file)} onClick={()=>void submit()}>{busy?<><LoaderCircle className="fc-spin"/>Posting…</>:<><Send/>Post</>}</button></footer></section></div>}</>;
}

function PostCard({post,own,menuOpen,onMenu,onDelete,onModerate,interactionBusy,onHeart,onSave,onShare,commentsOpen,comments,commentsMore,commentsLoading,onComments,onLoadMoreComments,onCommentCreated,onCommentDeleted}:{post:GlobalPost;own:boolean;menuOpen:boolean;onMenu:()=>void;onDelete:()=>void;onModerate:(action:"block"|"report")=>void;interactionBusy:boolean;onHeart:()=>void;onSave:()=>void;onShare:()=>void;commentsOpen:boolean;comments:GlobalComment[];commentsMore:boolean;commentsLoading:boolean;onComments:()=>void;onLoadMoreComments:()=>void;onCommentCreated:(comment:GlobalComment)=>void;onCommentDeleted:(comment:GlobalComment)=>void}){const[expanded,setExpanded]=useState(false);const longBody=Boolean(post.body&&post.body.length>280);return <article className="fc-global-post-card"><header><a href={`/profile/${post.userId}`} className="fc-global-post-author"><ProfileImage src={profilePhoto(post.photoKey)} alt={post.name}/><span><strong>{post.name}{post.verified&&<b aria-label="Verified">✓</b>}</strong><small>{post.username?`@${post.username}`:"Flirtschat member"} · {relativeTime(post.createdAt)}</small></span></a><div className="fc-global-post-menu"><button type="button" onClick={onMenu} aria-label="Post actions" aria-expanded={menuOpen}><MoreHorizontal/></button>{menuOpen&&<div role="menu">{own?<button type="button" role="menuitem" onClick={onDelete}><Trash2/>Delete post</button>:<><button type="button" role="menuitem" onClick={()=>onModerate("report")}>Report post</button><button type="button" role="menuitem" onClick={()=>onModerate("block")}>Block member</button></>}</div>}</div></header>{post.body&&<div className={`fc-global-post-copy ${expanded?"expanded":""}`}><p>{post.body}</p>{longBody&&<button type="button" onClick={()=>setExpanded(value=>!value)}>{expanded?"less":"more"}</button>}</div>}{post.imageKey&&<img className="fc-global-post-image" src={postImageUrl(post.imageKey)} alt={post.body||"Shared post image"} loading="lazy" draggable={false} onContextMenu={event=>event.preventDefault()}/>}<PostActions post={post} busy={interactionBusy} onHeart={onHeart} onComments={onComments} onShare={onShare} onSave={onSave}/>{commentsOpen&&<PostComments post={post} comments={comments} more={commentsMore} loading={commentsLoading} onLoadMore={onLoadMoreComments} onCreated={onCommentCreated} onDeleted={onCommentDeleted} onClose={onComments}/>}</article>}

const compactCount=(value:number)=>value<1000?String(value):`${Number((value/1000).toFixed(value<10000?1:0))}K`;
function PostActions({post,busy,onHeart,onComments,onShare,onSave}:{post:GlobalPost;busy:boolean;onHeart:()=>void;onComments:()=>void;onShare:()=>void;onSave:()=>void}){return <div className="fc-global-post-actions"><div className="fc-global-post-actions-left"><button type="button" className={post.heartedByMe?"hearted":""} onClick={onHeart} disabled={busy} aria-label={post.heartedByMe?"Remove heart":"Heart post"} aria-pressed={post.heartedByMe}><Heart fill={post.heartedByMe?"currentColor":"none"}/><span>{compactCount(post.heartCount)}</span></button><button type="button" onClick={onComments} aria-label="View comments"><MessageCircle/><span>{compactCount(post.commentCount)}</span></button><button type="button" onClick={onShare} aria-label="Share post"><Share2/><span>{compactCount(post.shareCount)}</span></button></div><button type="button" className={post.savedByMe?"saved":""} onClick={onSave} disabled={busy} aria-label={post.savedByMe?"Remove saved post":"Save post"} aria-pressed={post.savedByMe}><Bookmark fill={post.savedByMe?"currentColor":"none"}/><span className="sr-only">{post.savedByMe?"Saved":"Save"}</span></button></div>}

function PostComments({post,comments,more,loading,onLoadMore,onCreated,onDeleted,onClose}:{post:GlobalPost;comments:GlobalComment[];more:boolean;loading:boolean;onLoadMore:()=>void;onCreated:(comment:GlobalComment)=>void;onDeleted:(comment:GlobalComment)=>void;onClose:()=>void}){const[body,setBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const{profile}=useCurrentProfile();const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy||!body.trim())return;setBusy(true);setError("");try{onCreated(await createPostComment(post.id,body));setBody("")}catch{setError("Comment couldn’t be sent. Try again.")}finally{setBusy(false)}};return <div className="fc-global-comments-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="fc-global-comments" role="dialog" aria-modal="true" aria-labelledby={`comments-title-${post.id}`}><header><strong id={`comments-title-${post.id}`}>Comments</strong><button type="button" onClick={onClose} aria-label="Close comments"><X/></button></header><div className="fc-global-comment-list">{loading&&!comments.length&&<span className="fc-global-comment-loading">Loading comments…</span>}{comments.map(comment=><CommentRow key={comment.id} comment={comment} onDeleted={onDeleted}/>)}</div>{more&&<button type="button" className="fc-global-more-comments" onClick={onLoadMore} disabled={loading}>{loading?"Loading…":"View more comments"}</button>}<form onSubmit={event=>void submit(event)}><ProfileImage src={profile?.primaryPhotoUrl??null} alt="Your profile"/><input value={body} maxLength={1000} onChange={event=>setBody(event.target.value)} placeholder="Write a comment..." aria-label="Write a comment"/><button type="submit" disabled={busy||!body.trim()} aria-label="Send comment">{busy?<LoaderCircle className="fc-spin"/>:<Send/>}</button></form>{error&&<p className="fc-global-comment-error" role="alert">{error}</p>}</section></div>}
function CommentRow({comment,onDeleted}:{comment:GlobalComment;onDeleted:(comment:GlobalComment)=>void}){const{user}=useCurrentProfile(),[busy,setBusy]=useState(false);const remove=async()=>{if(busy)return;setBusy(true);try{await deletePostComment(comment.id);onDeleted(comment)}catch{/* keep the comment visible */}finally{setBusy(false)}};return <article className="fc-global-comment"><ProfileImage src={profilePhoto(comment.photoKey)} alt={comment.name}/><div><strong>{comment.name}</strong><p>{comment.body}</p><small>{relativeTime(comment.createdAt)}</small></div>{user?.id===comment.userId&&<button type="button" onClick={()=>void remove()} disabled={busy} aria-label={`Delete comment by ${comment.name}`}><Trash2/></button>}</article>}
